#nullable disable

using EventHub.Host.Views;

namespace EventHub.Host;

partial class HostDashboardForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        shellTableLayoutPanel = new TableLayoutPanel();
        headerTableLayoutPanel = new TableLayoutPanel();
        currentEventHeaderLabel = new Label();
        currentActivityHeaderLabel = new Label();
        currentQuizHeaderLabel = new Label();
        participantHeaderLabel = new Label();
        serverHeaderLabel = new Label();
        displayHeaderLabel = new Label();
        activityStateHeaderLabel = new Label();
        mainTableLayoutPanel = new TableLayoutPanel();
        navigationPanel = new Panel();
        brandLabel = new Label();
        dashboardNavigationButton = new Button();
        eventNavigationButton = new Button();
        questionBankNavigationButton = new Button();
        quizNavigationButton = new Button();
        contentPanel = new Panel();
        dashboardView = new DashboardView();
        eventManagementView = new EventManagementView();
        questionBankView = new QuestionBankView();
        quizActivityView = new QuizActivityView();
        liveMonitorView = new LiveMonitorView();
        actionTableLayoutPanel = new TableLayoutPanel();
        actionContextLabel = new Label();
        actionGuidanceLabel = new Label();
        primaryActionButton = new Button();
        actionStatusLabel = new Label();
        shellTableLayoutPanel.SuspendLayout();
        headerTableLayoutPanel.SuspendLayout();
        mainTableLayoutPanel.SuspendLayout();
        navigationPanel.SuspendLayout();
        contentPanel.SuspendLayout();
        actionTableLayoutPanel.SuspendLayout();
        SuspendLayout();
        shellTableLayoutPanel.ColumnCount = 1;
        shellTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        shellTableLayoutPanel.Controls.Add(headerTableLayoutPanel, 0, 0);
        shellTableLayoutPanel.Controls.Add(mainTableLayoutPanel, 0, 1);
        shellTableLayoutPanel.Controls.Add(actionTableLayoutPanel, 0, 2);
        shellTableLayoutPanel.Dock = DockStyle.Fill;
        shellTableLayoutPanel.Name = "shellTableLayoutPanel";
        shellTableLayoutPanel.RowCount = 3;
        shellTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
        shellTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        shellTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 80F));
        headerTableLayoutPanel.BackColor = Color.White;
        headerTableLayoutPanel.ColumnCount = 7;
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 11F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 11F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 9F));
        headerTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 10F));
        headerTableLayoutPanel.Controls.Add(currentEventHeaderLabel, 0, 0);
        headerTableLayoutPanel.Controls.Add(currentActivityHeaderLabel, 1, 0);
        headerTableLayoutPanel.Controls.Add(currentQuizHeaderLabel, 2, 0);
        headerTableLayoutPanel.Controls.Add(participantHeaderLabel, 3, 0);
        headerTableLayoutPanel.Controls.Add(serverHeaderLabel, 4, 0);
        headerTableLayoutPanel.Controls.Add(displayHeaderLabel, 5, 0);
        headerTableLayoutPanel.Controls.Add(activityStateHeaderLabel, 6, 0);
        headerTableLayoutPanel.Dock = DockStyle.Fill;
        headerTableLayoutPanel.Name = "headerTableLayoutPanel";
        headerTableLayoutPanel.Padding = new Padding(18, 10, 18, 10);
        headerTableLayoutPanel.RowCount = 1;
        headerTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        currentEventHeaderLabel.AutoEllipsis = true;
        currentEventHeaderLabel.Dock = DockStyle.Fill;
        currentEventHeaderLabel.Font = new Font("Microsoft JhengHei UI", 13F, FontStyle.Bold);
        currentEventHeaderLabel.Name = "currentEventHeaderLabel";
        currentEventHeaderLabel.Text = "Current Event：尚未選擇";
        currentEventHeaderLabel.TextAlign = ContentAlignment.MiddleLeft;
        currentActivityHeaderLabel.Dock = DockStyle.Fill;
        currentActivityHeaderLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        currentActivityHeaderLabel.Name = "currentActivityHeaderLabel";
        currentActivityHeaderLabel.Text = "Activity: Quiz";
        currentActivityHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        currentQuizHeaderLabel.AutoEllipsis = true;
        currentQuizHeaderLabel.Dock = DockStyle.Fill;
        currentQuizHeaderLabel.Name = "currentQuizHeaderLabel";
        currentQuizHeaderLabel.Text = "Quiz：尚未選擇";
        currentQuizHeaderLabel.TextAlign = ContentAlignment.MiddleLeft;
        participantHeaderLabel.Dock = DockStyle.Fill;
        participantHeaderLabel.Name = "participantHeaderLabel";
        participantHeaderLabel.Text = "Participants 0";
        participantHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        serverHeaderLabel.Dock = DockStyle.Fill;
        serverHeaderLabel.ForeColor = Color.Firebrick;
        serverHeaderLabel.Name = "serverHeaderLabel";
        serverHeaderLabel.Text = "● Server Disconnected";
        serverHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        displayHeaderLabel.Dock = DockStyle.Fill;
        displayHeaderLabel.Name = "displayHeaderLabel";
        displayHeaderLabel.Text = "Display: Waiting";
        displayHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        activityStateHeaderLabel.Dock = DockStyle.Fill;
        activityStateHeaderLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        activityStateHeaderLabel.Name = "activityStateHeaderLabel";
        activityStateHeaderLabel.Text = "WAITING";
        activityStateHeaderLabel.TextAlign = ContentAlignment.MiddleCenter;
        mainTableLayoutPanel.ColumnCount = 3;
        mainTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 160F));
        mainTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 250F));
        mainTableLayoutPanel.Controls.Add(navigationPanel, 0, 0);
        mainTableLayoutPanel.Controls.Add(contentPanel, 1, 0);
        mainTableLayoutPanel.Controls.Add(liveMonitorView, 2, 0);
        mainTableLayoutPanel.Dock = DockStyle.Fill;
        mainTableLayoutPanel.Name = "mainTableLayoutPanel";
        mainTableLayoutPanel.RowCount = 1;
        mainTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        navigationPanel.BackColor = Color.FromArgb(22, 43, 65);
        navigationPanel.Controls.Add(quizNavigationButton);
        navigationPanel.Controls.Add(questionBankNavigationButton);
        navigationPanel.Controls.Add(eventNavigationButton);
        navigationPanel.Controls.Add(dashboardNavigationButton);
        navigationPanel.Controls.Add(brandLabel);
        navigationPanel.Dock = DockStyle.Fill;
        navigationPanel.Name = "navigationPanel";
        brandLabel.Dock = DockStyle.Top;
        brandLabel.Font = new Font("Microsoft JhengHei UI", 15F, FontStyle.Bold);
        brandLabel.ForeColor = Color.White;
        brandLabel.Height = 60;
        brandLabel.Name = "brandLabel";
        brandLabel.Padding = new Padding(16, 20, 0, 0);
        brandLabel.Text = "EventHub";
        dashboardNavigationButton.BackColor = Color.FromArgb(22, 43, 65);
        dashboardNavigationButton.FlatAppearance.BorderSize = 0;
        dashboardNavigationButton.FlatStyle = FlatStyle.Flat;
        dashboardNavigationButton.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        dashboardNavigationButton.ForeColor = Color.WhiteSmoke;
        dashboardNavigationButton.Dock = DockStyle.Top;
        dashboardNavigationButton.Name = "dashboardNavigationButton";
        dashboardNavigationButton.Padding = new Padding(16, 0, 0, 0);
        dashboardNavigationButton.Height = 48;
        dashboardNavigationButton.Tag = HostView.Dashboard;
        dashboardNavigationButton.Text = "Dashboard";
        dashboardNavigationButton.TextAlign = ContentAlignment.MiddleLeft;
        dashboardNavigationButton.UseVisualStyleBackColor = false;
        dashboardNavigationButton.Click += navigationButton_Click;
        eventNavigationButton.BackColor = Color.FromArgb(22, 43, 65);
        eventNavigationButton.FlatAppearance.BorderSize = 0;
        eventNavigationButton.FlatStyle = FlatStyle.Flat;
        eventNavigationButton.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        eventNavigationButton.ForeColor = Color.WhiteSmoke;
        eventNavigationButton.Dock = DockStyle.Top;
        eventNavigationButton.Name = "eventNavigationButton";
        eventNavigationButton.Padding = new Padding(16, 0, 0, 0);
        eventNavigationButton.Height = 48;
        eventNavigationButton.Tag = HostView.Event;
        eventNavigationButton.Text = "Event";
        eventNavigationButton.TextAlign = ContentAlignment.MiddleLeft;
        eventNavigationButton.UseVisualStyleBackColor = false;
        eventNavigationButton.Click += navigationButton_Click;
        questionBankNavigationButton.BackColor = Color.FromArgb(22, 43, 65);
        questionBankNavigationButton.FlatAppearance.BorderSize = 0;
        questionBankNavigationButton.FlatStyle = FlatStyle.Flat;
        questionBankNavigationButton.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        questionBankNavigationButton.ForeColor = Color.WhiteSmoke;
        questionBankNavigationButton.Dock = DockStyle.Top;
        questionBankNavigationButton.Name = "questionBankNavigationButton";
        questionBankNavigationButton.Padding = new Padding(16, 0, 0, 0);
        questionBankNavigationButton.Height = 48;
        questionBankNavigationButton.Tag = HostView.QuestionBank;
        questionBankNavigationButton.Text = "Question Bank";
        questionBankNavigationButton.TextAlign = ContentAlignment.MiddleLeft;
        questionBankNavigationButton.UseVisualStyleBackColor = false;
        questionBankNavigationButton.Click += navigationButton_Click;
        quizNavigationButton.BackColor = Color.FromArgb(22, 43, 65);
        quizNavigationButton.FlatAppearance.BorderSize = 0;
        quizNavigationButton.FlatStyle = FlatStyle.Flat;
        quizNavigationButton.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        quizNavigationButton.ForeColor = Color.WhiteSmoke;
        quizNavigationButton.Dock = DockStyle.Top;
        quizNavigationButton.Name = "quizNavigationButton";
        quizNavigationButton.Padding = new Padding(16, 0, 0, 0);
        quizNavigationButton.Height = 48;
        quizNavigationButton.Tag = HostView.Quiz;
        quizNavigationButton.Text = "Quiz Activity";
        quizNavigationButton.TextAlign = ContentAlignment.MiddleLeft;
        quizNavigationButton.UseVisualStyleBackColor = false;
        quizNavigationButton.Click += navigationButton_Click;
        contentPanel.BackColor = Color.FromArgb(244, 247, 250);
        contentPanel.Controls.Add(quizActivityView);
        contentPanel.Controls.Add(questionBankView);
        contentPanel.Controls.Add(eventManagementView);
        contentPanel.Controls.Add(dashboardView);
        contentPanel.Dock = DockStyle.Fill;
        contentPanel.Name = "contentPanel";
        contentPanel.Padding = new Padding(6);
        dashboardView.Dock = DockStyle.Fill;
        dashboardView.Name = "dashboardView";
        eventManagementView.Dock = DockStyle.Fill;
        eventManagementView.Name = "eventManagementView";
        eventManagementView.Visible = false;
        questionBankView.Dock = DockStyle.Fill;
        questionBankView.Name = "questionBankView";
        questionBankView.Visible = false;
        quizActivityView.Dock = DockStyle.Fill;
        quizActivityView.Name = "quizActivityView";
        quizActivityView.Visible = false;
        liveMonitorView.Dock = DockStyle.Fill;
        liveMonitorView.Name = "liveMonitorView";
        actionTableLayoutPanel.BackColor = Color.White;
        actionTableLayoutPanel.ColumnCount = 4;
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 22F));
        actionTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
        actionTableLayoutPanel.Controls.Add(actionContextLabel, 0, 0);
        actionTableLayoutPanel.Controls.Add(actionGuidanceLabel, 1, 0);
        actionTableLayoutPanel.Controls.Add(primaryActionButton, 2, 0);
        actionTableLayoutPanel.Controls.Add(actionStatusLabel, 3, 0);
        actionTableLayoutPanel.Dock = DockStyle.Fill;
        actionTableLayoutPanel.Name = "actionTableLayoutPanel";
        actionTableLayoutPanel.Padding = new Padding(18, 10, 18, 10);
        actionTableLayoutPanel.RowCount = 1;
        actionTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        actionContextLabel.AutoEllipsis = true;
        actionContextLabel.Dock = DockStyle.Fill;
        actionContextLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        actionContextLabel.Name = "actionContextLabel";
        actionContextLabel.Text = "尚未選擇題目";
        actionContextLabel.TextAlign = ContentAlignment.MiddleLeft;
        actionGuidanceLabel.AutoEllipsis = true;
        actionGuidanceLabel.Dock = DockStyle.Fill;
        actionGuidanceLabel.Name = "actionGuidanceLabel";
        actionGuidanceLabel.Text = "請先載入題庫並選擇題目。";
        actionGuidanceLabel.TextAlign = ContentAlignment.MiddleLeft;
        primaryActionButton.BackColor = Color.FromArgb(19, 132, 99);
        primaryActionButton.Dock = DockStyle.Fill;
        primaryActionButton.Enabled = false;
        primaryActionButton.FlatAppearance.BorderSize = 0;
        primaryActionButton.FlatStyle = FlatStyle.Flat;
        primaryActionButton.Font = new Font("Microsoft JhengHei UI", 12F, FontStyle.Bold);
        primaryActionButton.ForeColor = Color.White;
        primaryActionButton.Margin = new Padding(8);
        primaryActionButton.Name = "primaryActionButton";
        primaryActionButton.Text = "開始本題";
        primaryActionButton.UseVisualStyleBackColor = false;
        primaryActionButton.Click += primaryActionButton_Click;
        actionStatusLabel.AutoEllipsis = true;
        actionStatusLabel.Dock = DockStyle.Fill;
        actionStatusLabel.Name = "actionStatusLabel";
        actionStatusLabel.Text = "等待操作";
        actionStatusLabel.TextAlign = ContentAlignment.MiddleCenter;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        ClientSize = new Size(1180, 680);
        Controls.Add(shellTableLayoutPanel);
        MinimumSize = new Size(1024, 640);
        Name = "HostDashboardForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "EventHub Host Console";
        FormClosed += HostDashboardForm_FormClosed;
        shellTableLayoutPanel.ResumeLayout(false);
        headerTableLayoutPanel.ResumeLayout(false);
        mainTableLayoutPanel.ResumeLayout(false);
        navigationPanel.ResumeLayout(false);
        contentPanel.ResumeLayout(false);
        actionTableLayoutPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

    private TableLayoutPanel shellTableLayoutPanel;
    private TableLayoutPanel headerTableLayoutPanel;
    private Label currentEventHeaderLabel;
    private Label currentActivityHeaderLabel;
    private Label currentQuizHeaderLabel;
    private Label participantHeaderLabel;
    private Label serverHeaderLabel;
    private Label displayHeaderLabel;
    private Label activityStateHeaderLabel;
    private TableLayoutPanel mainTableLayoutPanel;
    private Panel navigationPanel;
    private Label brandLabel;
    private Button dashboardNavigationButton;
    private Button eventNavigationButton;
    private Button questionBankNavigationButton;
    private Button quizNavigationButton;
    private Panel contentPanel;
    private DashboardView dashboardView;
    private EventManagementView eventManagementView;
    private QuestionBankView questionBankView;
    private QuizActivityView quizActivityView;
    private LiveMonitorView liveMonitorView;
    private TableLayoutPanel actionTableLayoutPanel;
    private Label actionContextLabel;
    private Label actionGuidanceLabel;
    private Button primaryActionButton;
    private Label actionStatusLabel;
}
