#nullable disable

namespace EventHub.Host.Views;

partial class EventManagementView
{
    private System.ComponentModel.IContainer components;

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        eventIdToolTip = new ToolTip(components);
        rootLayoutPanel = new TableLayoutPanel();
        titleLabel = new Label();
        operationMessagePanel = new Panel();
        statusLabel = new Label();
        subtitleLabel = new Label();
        currentEventPanel = new Panel();
        currentEventTitleLabel = new Label();
        currentEventTableLayoutPanel = new TableLayoutPanel();
        currentEventNameCaptionLabel = new Label();
        currentEventNameValueLabel = new Label();
        currentEventDateCaptionLabel = new Label();
        currentEventDateValueLabel = new Label();
        currentEventStatusCaptionLabel = new Label();
        currentEventStatusValueLabel = new Label();
        currentEventIdCaptionLabel = new Label();
        currentEventIdValueLabel = new Label();
        copyEventIdButton = new Button();
        mobileJoinPanel = new Panel();
        mobileJoinTitleLabel = new Label();
        mobileJoinTableLayoutPanel = new TableLayoutPanel();
        joinCodeCaptionLabel = new Label();
        joinCodeValueLabel = new Label();
        copyJoinCodeButton = new Button();
        joinUrlCaptionLabel = new Label();
        joinUrlTextBox = new TextBox();
        copyJoinUrlButton = new Button();
        joinUrlWarningLabel = new Label();
        joinQrCodePictureBox = new PictureBox();
        eventSetupPanel = new Panel();
        eventSetupTitleLabel = new Label();
        eventSetupTableLayoutPanel = new TableLayoutPanel();
        eventNameLabel = new Label();
        eventNameTextBox = new TextBox();
        eventDateLabel = new Label();
        eventDatePicker = new DateTimePicker();
        createEventButton = new Button();
        existingEventHintLabel = new Label();
        eventIdLabel = new Label();
        eventIdTextBox = new TextBox();
        hostTokenLabel = new Label();
        hostTokenTextBox = new TextBox();
        connectButton = new Button();
        networkStatusPanel = new Panel();
        networkStatusTitleLabel = new Label();
        networkTableLayoutPanel = new TableLayoutPanel();
        lanAddressLabel = new Label();
        lanAddressComboBox = new ComboBox();
        refreshLanAddressesButton = new Button();
        serverUrlLabel = new Label();
        serverUrlTextBox = new TextBox();
        networkReadyCaptionLabel = new Label();
        networkReadyValueLabel = new Label();
        serverStatusCaptionLabel = new Label();
        serverStatusValueLabel = new Label();
        firewallStatusCaptionLabel = new Label();
        firewallStatusValueLabel = new Label();
        testConnectionButton = new Button();
        installFirewallRuleButton = new Button();
        participantsPanel = new Panel();
        participantsTableLayoutPanel = new TableLayoutPanel();
        participantsTitleLabel = new Label();
        participantEmptyLabel = new Label();
        participantGrid = new DataGridView();
        rootLayoutPanel.SuspendLayout();
        operationMessagePanel.SuspendLayout();
        currentEventPanel.SuspendLayout();
        currentEventTableLayoutPanel.SuspendLayout();
        mobileJoinPanel.SuspendLayout();
        mobileJoinTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)joinQrCodePictureBox).BeginInit();
        eventSetupPanel.SuspendLayout();
        eventSetupTableLayoutPanel.SuspendLayout();
        networkStatusPanel.SuspendLayout();
        networkTableLayoutPanel.SuspendLayout();
        participantsPanel.SuspendLayout();
        participantsTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)participantGrid).BeginInit();
        SuspendLayout();

        rootLayoutPanel.AutoSize = true;
        rootLayoutPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        rootLayoutPanel.ColumnCount = 1;
        rootLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayoutPanel.Controls.Add(titleLabel, 0, 0);
        rootLayoutPanel.Controls.Add(subtitleLabel, 0, 1);
        rootLayoutPanel.Controls.Add(operationMessagePanel, 0, 2);
        rootLayoutPanel.Controls.Add(networkStatusPanel, 0, 3);
        rootLayoutPanel.Controls.Add(eventSetupPanel, 0, 4);
        rootLayoutPanel.Controls.Add(currentEventPanel, 0, 5);
        rootLayoutPanel.Controls.Add(mobileJoinPanel, 0, 6);
        rootLayoutPanel.Controls.Add(participantsPanel, 0, 7);
        rootLayoutPanel.Dock = DockStyle.Top;
        rootLayoutPanel.Name = "rootLayoutPanel";
        rootLayoutPanel.RowCount = 8;
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 250F));
        titleLabel.AutoSize = true;
        titleLabel.Dock = DockStyle.Top;
        titleLabel.Font = new Font("Microsoft JhengHei UI", 20F, FontStyle.Bold);
        titleLabel.Name = "titleLabel";
        titleLabel.Text = "活動與參與者";
        titleLabel.TextAlign = ContentAlignment.MiddleLeft;
        subtitleLabel.AutoSize = true;
        subtitleLabel.Dock = DockStyle.Top;
        subtitleLabel.ForeColor = Color.DimGray;
        subtitleLabel.Name = "subtitleLabel";
        subtitleLabel.Text = "完成網路設定、建立活動並確認參與者加入";
        subtitleLabel.TextAlign = ContentAlignment.MiddleLeft;
        operationMessagePanel.BackColor = Color.FromArgb(240, 246, 252);
        operationMessagePanel.AutoSize = true;
        operationMessagePanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        operationMessagePanel.Controls.Add(statusLabel);
        operationMessagePanel.Dock = DockStyle.Top;
        operationMessagePanel.Margin = new Padding(0, 4, 0, 6);
        operationMessagePanel.Name = "operationMessagePanel";
        operationMessagePanel.Padding = new Padding(14, 8, 14, 8);
        statusLabel.AutoEllipsis = false;
        statusLabel.AutoSize = true;
        statusLabel.Dock = DockStyle.Top;
        statusLabel.Name = "statusLabel";
        statusLabel.Text = "● 尚未連線至活動";
        statusLabel.TextAlign = ContentAlignment.MiddleLeft;

        currentEventPanel.Name = "currentEventPanel";
        ConfigureSectionPanel(currentEventPanel);
        currentEventPanel.Controls.Add(currentEventTableLayoutPanel);
        currentEventPanel.Controls.Add(currentEventTitleLabel);
        currentEventTitleLabel.Name = "currentEventTitleLabel";
        ConfigureSectionTitle(currentEventTitleLabel, "STEP 3　目前活動　○ 尚未連線");
        ConfigureDetailsTable(currentEventTableLayoutPanel);
        currentEventTableLayoutPanel.Controls.Add(currentEventNameCaptionLabel, 0, 0);
        currentEventTableLayoutPanel.Controls.Add(currentEventNameValueLabel, 1, 0);
        currentEventTableLayoutPanel.SetColumnSpan(currentEventNameValueLabel, 2);
        currentEventTableLayoutPanel.Controls.Add(currentEventDateCaptionLabel, 0, 1);
        currentEventTableLayoutPanel.Controls.Add(currentEventDateValueLabel, 1, 1);
        currentEventTableLayoutPanel.SetColumnSpan(currentEventDateValueLabel, 2);
        currentEventTableLayoutPanel.Controls.Add(currentEventStatusCaptionLabel, 0, 2);
        currentEventTableLayoutPanel.Controls.Add(currentEventStatusValueLabel, 1, 2);
        currentEventTableLayoutPanel.SetColumnSpan(currentEventStatusValueLabel, 2);
        currentEventTableLayoutPanel.Controls.Add(currentEventIdCaptionLabel, 0, 3);
        currentEventTableLayoutPanel.Controls.Add(currentEventIdValueLabel, 1, 3);
        currentEventTableLayoutPanel.Controls.Add(copyEventIdButton, 2, 3);
        currentEventTableLayoutPanel.RowCount = 4;
        currentEventTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        currentEventTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        currentEventTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        currentEventTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        ConfigureCaption(currentEventNameCaptionLabel, "活動");
        ConfigureValue(currentEventNameValueLabel, "尚未選擇", 15F, true);
        ConfigureCaption(currentEventDateCaptionLabel, "日期");
        ConfigureValue(currentEventDateValueLabel, "—");
        ConfigureCaption(currentEventStatusCaptionLabel, "狀態");
        ConfigureValue(currentEventStatusValueLabel, "● 尚未連線");
        ConfigureCaption(currentEventIdCaptionLabel, "Event ID");
        ConfigureValue(currentEventIdValueLabel, "—", 9F);
        copyEventIdButton.Name = "copyEventIdButton";
        ConfigureCopyButton(copyEventIdButton, "複製", copyEventIdButton_Click);
        eventIdToolTip.SetToolTip(currentEventIdValueLabel, "尚未選擇活動");

        mobileJoinPanel.Name = "mobileJoinPanel";
        ConfigureSectionPanel(mobileJoinPanel);
        mobileJoinPanel.Controls.Add(mobileJoinTableLayoutPanel);
        mobileJoinPanel.Controls.Add(mobileJoinTitleLabel);
        mobileJoinTitleLabel.Name = "mobileJoinTitleLabel";
        ConfigureSectionTitle(mobileJoinTitleLabel, "STEP 4　手機加入　○ 尚未準備");
        mobileJoinTableLayoutPanel.ColumnCount = 3;
        mobileJoinTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 68F));
        mobileJoinTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mobileJoinTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        mobileJoinTableLayoutPanel.Controls.Add(joinCodeCaptionLabel, 0, 0);
        mobileJoinTableLayoutPanel.Controls.Add(joinCodeValueLabel, 1, 0);
        mobileJoinTableLayoutPanel.Controls.Add(copyJoinCodeButton, 2, 0);
        mobileJoinTableLayoutPanel.Controls.Add(joinUrlCaptionLabel, 0, 1);
        mobileJoinTableLayoutPanel.Controls.Add(joinUrlTextBox, 1, 1);
        mobileJoinTableLayoutPanel.Controls.Add(copyJoinUrlButton, 2, 1);
        mobileJoinTableLayoutPanel.Controls.Add(joinUrlWarningLabel, 0, 2);
        mobileJoinTableLayoutPanel.SetColumnSpan(joinUrlWarningLabel, 2);
        mobileJoinTableLayoutPanel.Controls.Add(joinQrCodePictureBox, 2, 2);
        mobileJoinTableLayoutPanel.AutoSize = true;
        mobileJoinTableLayoutPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        mobileJoinTableLayoutPanel.Dock = DockStyle.Top;
        mobileJoinTableLayoutPanel.Padding = new Padding(0, 30, 0, 0);
        mobileJoinTableLayoutPanel.Name = "mobileJoinTableLayoutPanel";
        mobileJoinTableLayoutPanel.RowCount = 3;
        mobileJoinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mobileJoinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        mobileJoinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        ConfigureCaption(joinCodeCaptionLabel, "加入碼");
        ConfigureValue(joinCodeValueLabel, "— — — — — —", 18F, true);
        joinCodeValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        copyJoinCodeButton.Name = "copyJoinCodeButton";
        ConfigureCopyButton(copyJoinCodeButton, "複製", copyJoinCodeButton_Click);
        ConfigureCaption(joinUrlCaptionLabel, "網址");
        joinUrlTextBox.Dock = DockStyle.Fill;
        joinUrlTextBox.Name = "joinUrlTextBox";
        joinUrlTextBox.ReadOnly = true;
        copyJoinUrlButton.Name = "copyJoinUrlButton";
        ConfigureCopyButton(copyJoinUrlButton, "複製", copyJoinUrlButton_Click);
        joinUrlWarningLabel.Dock = DockStyle.Fill;
        joinUrlWarningLabel.AutoSize = true;
        joinUrlWarningLabel.Name = "joinUrlWarningLabel";
        joinUrlWarningLabel.Text = "建立或連線活動後，這裡會顯示加入資訊。";
        joinQrCodePictureBox.BackColor = Color.White;
        joinQrCodePictureBox.Dock = DockStyle.Fill;
        joinQrCodePictureBox.Margin = new Padding(4);
        joinQrCodePictureBox.MinimumSize = new Size(132, 132);
        joinQrCodePictureBox.Name = "joinQrCodePictureBox";
        joinQrCodePictureBox.SizeMode = PictureBoxSizeMode.Zoom;

        eventSetupPanel.Name = "eventSetupPanel";
        ConfigureSectionPanel(eventSetupPanel);
        eventSetupPanel.Controls.Add(eventSetupTableLayoutPanel);
        eventSetupPanel.Controls.Add(eventSetupTitleLabel);
        eventSetupTitleLabel.Name = "eventSetupTitleLabel";
        ConfigureSectionTitle(eventSetupTitleLabel, "STEP 2　建立或連線活動　○ 尚未完成");
        eventSetupTableLayoutPanel.ColumnCount = 4;
        eventSetupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 68F));
        eventSetupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        eventSetupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 76F));
        eventSetupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        eventSetupTableLayoutPanel.Controls.Add(eventNameLabel, 0, 0);
        eventSetupTableLayoutPanel.Controls.Add(eventNameTextBox, 1, 0);
        eventSetupTableLayoutPanel.Controls.Add(eventDateLabel, 2, 0);
        eventSetupTableLayoutPanel.Controls.Add(eventDatePicker, 3, 0);
        eventSetupTableLayoutPanel.Controls.Add(createEventButton, 1, 1);
        eventSetupTableLayoutPanel.SetColumnSpan(createEventButton, 3);
        eventSetupTableLayoutPanel.Controls.Add(existingEventHintLabel, 0, 2);
        eventSetupTableLayoutPanel.SetColumnSpan(existingEventHintLabel, 4);
        eventSetupTableLayoutPanel.Controls.Add(eventIdLabel, 0, 3);
        eventSetupTableLayoutPanel.Controls.Add(eventIdTextBox, 1, 3);
        eventSetupTableLayoutPanel.Controls.Add(hostTokenLabel, 2, 3);
        eventSetupTableLayoutPanel.Controls.Add(hostTokenTextBox, 3, 3);
        eventSetupTableLayoutPanel.Controls.Add(connectButton, 1, 4);
        eventSetupTableLayoutPanel.SetColumnSpan(connectButton, 3);
        eventSetupTableLayoutPanel.AutoSize = true;
        eventSetupTableLayoutPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        eventSetupTableLayoutPanel.Dock = DockStyle.Top;
        eventSetupTableLayoutPanel.Padding = new Padding(0, 30, 0, 0);
        eventSetupTableLayoutPanel.Name = "eventSetupTableLayoutPanel";
        eventSetupTableLayoutPanel.RowCount = 5;
        eventSetupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        eventSetupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        eventSetupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        eventSetupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        eventSetupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        ConfigureCaption(eventNameLabel, "活動名稱");
        eventNameTextBox.Dock = DockStyle.Fill;
        eventNameTextBox.Name = "eventNameTextBox";
        eventNameTextBox.Text = "公司活動";
        ConfigureCaption(eventDateLabel, "活動日期");
        eventDatePicker.CustomFormat = "yyyy/MM/dd HH:mm";
        eventDatePicker.Dock = DockStyle.Fill;
        eventDatePicker.Format = DateTimePickerFormat.Custom;
        eventDatePicker.Name = "eventDatePicker";
        createEventButton.BackColor = Color.FromArgb(19, 132, 99);
        createEventButton.Dock = DockStyle.Fill;
        createEventButton.FlatAppearance.BorderSize = 0;
        createEventButton.FlatStyle = FlatStyle.Flat;
        createEventButton.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        createEventButton.ForeColor = Color.White;
        createEventButton.Margin = new Padding(3, 4, 3, 4);
        createEventButton.MinimumSize = new Size(0, 40);
        createEventButton.Name = "createEventButton";
        createEventButton.Text = "建立新活動";
        createEventButton.Click += createEventButton_Click;
        existingEventHintLabel.Dock = DockStyle.Fill;
        existingEventHintLabel.AutoSize = true;
        existingEventHintLabel.ForeColor = Color.DimGray;
        existingEventHintLabel.Name = "existingEventHintLabel";
        existingEventHintLabel.Text = "管理資訊｜已有活動時輸入 Event ID 與 Host Token";
        ConfigureCaption(eventIdLabel, "Event ID");
        eventIdTextBox.Dock = DockStyle.Fill;
        eventIdTextBox.Name = "eventIdTextBox";
        ConfigureCaption(hostTokenLabel, "Host Token");
        hostTokenTextBox.Dock = DockStyle.Fill;
        hostTokenTextBox.Name = "hostTokenTextBox";
        hostTokenTextBox.PasswordChar = '●';
        connectButton.Dock = DockStyle.Fill;
        connectButton.FlatStyle = FlatStyle.Flat;
        connectButton.MinimumSize = new Size(0, 36);
        connectButton.Name = "connectButton";
        connectButton.Text = "連線既有活動";
        connectButton.Click += connectButton_Click;

        networkStatusPanel.Name = "networkStatusPanel";
        ConfigureSectionPanel(networkStatusPanel);
        networkStatusPanel.Controls.Add(networkTableLayoutPanel);
        networkStatusPanel.Controls.Add(networkStatusTitleLabel);
        networkStatusTitleLabel.Name = "networkStatusTitleLabel";
        ConfigureSectionTitle(networkStatusTitleLabel, "STEP 1　活動網路　⚠ 尚未準備完成");
        networkTableLayoutPanel.ColumnCount = 4;
        networkTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 68F));
        networkTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        networkTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 82F));
        networkTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
        networkTableLayoutPanel.Controls.Add(lanAddressLabel, 0, 0);
        networkTableLayoutPanel.Controls.Add(lanAddressComboBox, 1, 0);
        networkTableLayoutPanel.Controls.Add(refreshLanAddressesButton, 2, 0);
        networkTableLayoutPanel.Controls.Add(testConnectionButton, 3, 0);
        networkTableLayoutPanel.Controls.Add(serverUrlLabel, 0, 1);
        networkTableLayoutPanel.Controls.Add(serverUrlTextBox, 1, 1);
        networkTableLayoutPanel.SetColumnSpan(serverUrlTextBox, 3);
        networkTableLayoutPanel.Controls.Add(networkReadyCaptionLabel, 0, 2);
        networkTableLayoutPanel.Controls.Add(networkReadyValueLabel, 1, 2);
        networkTableLayoutPanel.SetColumnSpan(networkReadyValueLabel, 3);
        networkTableLayoutPanel.Controls.Add(serverStatusCaptionLabel, 0, 3);
        networkTableLayoutPanel.Controls.Add(serverStatusValueLabel, 1, 3);
        networkTableLayoutPanel.Controls.Add(firewallStatusCaptionLabel, 2, 3);
        networkTableLayoutPanel.Controls.Add(firewallStatusValueLabel, 3, 3);
        networkTableLayoutPanel.Controls.Add(installFirewallRuleButton, 1, 4);
        networkTableLayoutPanel.SetColumnSpan(installFirewallRuleButton, 3);
        networkTableLayoutPanel.AutoSize = true;
        networkTableLayoutPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        networkTableLayoutPanel.Dock = DockStyle.Top;
        networkTableLayoutPanel.Padding = new Padding(0, 30, 0, 0);
        networkTableLayoutPanel.Name = "networkTableLayoutPanel";
        networkTableLayoutPanel.RowCount = 5;
        networkTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        networkTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        networkTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        networkTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        networkTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        ConfigureCaption(lanAddressLabel, "活動網路");
        lanAddressComboBox.Dock = DockStyle.Fill;
        lanAddressComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        lanAddressComboBox.Name = "lanAddressComboBox";
        lanAddressComboBox.SelectedIndexChanged += lanAddressComboBox_SelectedIndexChanged;
        refreshLanAddressesButton.Name = "refreshLanAddressesButton";
        ConfigureSecondaryButton(refreshLanAddressesButton, "重新掃描", refreshLanAddressesButton_Click);
        testConnectionButton.Name = "testConnectionButton";
        ConfigureSecondaryButton(testConnectionButton, "連線檢查", testConnectionButton_Click);
        ConfigureCaption(serverUrlLabel, "本機 Server");
        serverUrlTextBox.Dock = DockStyle.Fill;
        serverUrlTextBox.Name = "serverUrlTextBox";
        serverUrlTextBox.Text = "http://localhost:5000";
        ConfigureCaption(networkReadyCaptionLabel, "Guest");
        ConfigureValue(networkReadyValueLabel, "尚未偵測活動網路");
        ConfigureCaption(serverStatusCaptionLabel, "Server");
        ConfigureValue(serverStatusValueLabel, "● Disconnected");
        ConfigureCaption(firewallStatusCaptionLabel, "Firewall");
        ConfigureValue(firewallStatusValueLabel, "尚未檢查", 9F);
        installFirewallRuleButton.Name = "installFirewallRuleButton";
        ConfigureSecondaryButton(installFirewallRuleButton, "建立 Firewall Rule", installFirewallRuleButton_Click);

        participantsPanel.BackColor = Color.White;
        participantsPanel.Controls.Add(participantsTableLayoutPanel);
        participantsPanel.Dock = DockStyle.Fill;
        participantsPanel.Margin = new Padding(4, 8, 4, 4);
        participantsPanel.Name = "participantsPanel";
        participantsPanel.Padding = new Padding(12, 8, 12, 12);
        participantsTableLayoutPanel.ColumnCount = 1;
        participantsTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        participantsTableLayoutPanel.Controls.Add(participantsTitleLabel, 0, 0);
        participantsTableLayoutPanel.Controls.Add(participantEmptyLabel, 0, 1);
        participantsTableLayoutPanel.Controls.Add(participantGrid, 0, 2);
        participantsTableLayoutPanel.Dock = DockStyle.Fill;
        participantsTableLayoutPanel.Name = "participantsTableLayoutPanel";
        participantsTableLayoutPanel.RowCount = 3;
        participantsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        participantsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        participantsTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        participantsTitleLabel.Dock = DockStyle.Fill;
        participantsTitleLabel.Font = new Font("Microsoft JhengHei UI", 12F, FontStyle.Bold);
        participantsTitleLabel.Name = "participantsTitleLabel";
        participantsTitleLabel.Text = "STEP 5　參與者　0 位已加入";
        participantEmptyLabel.Dock = DockStyle.Fill;
        participantEmptyLabel.ForeColor = Color.DimGray;
        participantEmptyLabel.Name = "participantEmptyLabel";
        participantEmptyLabel.Text = "尚未有參與者加入";
        participantGrid.AllowUserToAddRows = false;
        participantGrid.AllowUserToDeleteRows = false;
        participantGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        participantGrid.Columns.AddRange(
            new DataGridViewTextBoxColumn { HeaderText = "顯示名稱" },
            new DataGridViewTextBoxColumn { HeaderText = "員工編號" },
            new DataGridViewTextBoxColumn { HeaderText = "部門" },
            new DataGridViewTextBoxColumn { HeaderText = "桌次" },
            new DataGridViewTextBoxColumn { HeaderText = "狀態" },
            new DataGridViewTextBoxColumn { HeaderText = "分數" });
        participantGrid.Dock = DockStyle.Fill;
        participantGrid.Name = "participantGrid";
        participantGrid.ReadOnly = true;
        participantGrid.RowHeadersVisible = false;

        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        BackColor = Color.FromArgb(244, 247, 250);
        Controls.Add(rootLayoutPanel);
        Name = "EventManagementView";
        Padding = new Padding(12);
        Size = new Size(984, 728);
        rootLayoutPanel.ResumeLayout(false);
        operationMessagePanel.ResumeLayout(false);
        currentEventPanel.ResumeLayout(false);
        currentEventTableLayoutPanel.ResumeLayout(false);
        mobileJoinPanel.ResumeLayout(false);
        mobileJoinTableLayoutPanel.ResumeLayout(false);
        mobileJoinTableLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)joinQrCodePictureBox).EndInit();
        eventSetupPanel.ResumeLayout(false);
        eventSetupTableLayoutPanel.ResumeLayout(false);
        eventSetupTableLayoutPanel.PerformLayout();
        networkStatusPanel.ResumeLayout(false);
        networkTableLayoutPanel.ResumeLayout(false);
        networkTableLayoutPanel.PerformLayout();
        participantsPanel.ResumeLayout(false);
        participantsTableLayoutPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)participantGrid).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    private static void ConfigureSectionPanel(Panel panel) { panel.AutoSize = true; panel.AutoSizeMode = AutoSizeMode.GrowAndShrink; panel.BackColor = Color.White; panel.Dock = DockStyle.Top; panel.Margin = new Padding(4, 6, 4, 6); panel.Padding = new Padding(12); }
    private static void ConfigureSectionTitle(Label label, string text) { label.Dock = DockStyle.Top; label.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold); label.ForeColor = Color.FromArgb(35, 67, 92); label.Height = 28; label.Text = text; }
    private static void ConfigureDetailsTable(TableLayoutPanel table) { table.AutoSize = true; table.AutoSizeMode = AutoSizeMode.GrowAndShrink; table.ColumnCount = 3; table.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 68F)); table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); table.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 64F)); table.Dock = DockStyle.Top; table.Padding = new Padding(0, 30, 0, 0); }
    private static void ConfigureCaption(Label label, string text) { label.AutoSize = true; label.Dock = DockStyle.Fill; label.ForeColor = Color.DimGray; label.MinimumSize = new Size(0, 30); label.Text = text; label.TextAlign = ContentAlignment.MiddleLeft; }
    private static void ConfigureValue(Label label, string text, float fontSize = 10F, bool isBold = false) { label.AutoEllipsis = true; label.AutoSize = true; label.Dock = DockStyle.Fill; label.Font = new Font("Microsoft JhengHei UI", fontSize, isBold ? FontStyle.Bold : FontStyle.Regular); label.ForeColor = Color.FromArgb(24, 50, 79); label.MinimumSize = new Size(0, 30); label.Text = text; label.TextAlign = ContentAlignment.MiddleLeft; }
    private static void ConfigureCopyButton(Button button, string text, EventHandler handler) { ConfigureSecondaryButton(button, text, handler); button.Margin = new Padding(3, 4, 3, 4); }
    private static void ConfigureSecondaryButton(Button button, string text, EventHandler handler) { button.AutoSize = true; button.Dock = DockStyle.Fill; button.FlatStyle = FlatStyle.Flat; button.Font = new Font("Microsoft JhengHei UI", 9F); button.Margin = new Padding(3); button.MinimumSize = new Size(0, 36); button.Text = text; button.Click += handler; }

    private ToolTip eventIdToolTip;
    private TableLayoutPanel rootLayoutPanel, currentEventTableLayoutPanel, mobileJoinTableLayoutPanel, eventSetupTableLayoutPanel, networkTableLayoutPanel, participantsTableLayoutPanel;
    private Panel operationMessagePanel, currentEventPanel, mobileJoinPanel, eventSetupPanel, networkStatusPanel, participantsPanel;
    private Label titleLabel, subtitleLabel, statusLabel, currentEventTitleLabel, currentEventNameCaptionLabel, currentEventNameValueLabel, currentEventDateCaptionLabel, currentEventDateValueLabel, currentEventStatusCaptionLabel, currentEventStatusValueLabel, currentEventIdCaptionLabel, currentEventIdValueLabel;
    private Label mobileJoinTitleLabel, joinCodeCaptionLabel, joinCodeValueLabel, joinUrlCaptionLabel, joinUrlWarningLabel;
    private Label eventSetupTitleLabel, eventNameLabel, eventDateLabel, existingEventHintLabel, eventIdLabel, hostTokenLabel;
    private Label networkStatusTitleLabel, lanAddressLabel, serverUrlLabel, networkReadyCaptionLabel, networkReadyValueLabel, serverStatusCaptionLabel, serverStatusValueLabel, firewallStatusCaptionLabel, firewallStatusValueLabel;
    private Label participantsTitleLabel, participantEmptyLabel;
    private Button copyEventIdButton, copyJoinCodeButton, copyJoinUrlButton, createEventButton, connectButton, refreshLanAddressesButton, testConnectionButton, installFirewallRuleButton;
    private TextBox joinUrlTextBox, eventNameTextBox, eventIdTextBox, hostTokenTextBox, serverUrlTextBox;
    private DateTimePicker eventDatePicker;
    private ComboBox lanAddressComboBox;
    private PictureBox joinQrCodePictureBox;
    private DataGridView participantGrid;
}
