#nullable disable

namespace EventHub.Host.Views;

partial class EventManagementView
{
    private void InitializeComponent()
    {
        titleLabel = new Label();
        setupGroupBox = new GroupBox();
        setupTableLayoutPanel = new TableLayoutPanel();
        lanAddressLabel = new Label();
        lanAddressComboBox = new ComboBox();
        refreshLanAddressesButton = new Button();
        testConnectionButton = new Button();
        serverUrlLabel = new Label();
        serverUrlTextBox = new TextBox();
        installFirewallRuleButton = new Button();
        eventNameLabel = new Label();
        eventNameTextBox = new TextBox();
        eventDateLabel = new Label();
        eventDatePicker = new DateTimePicker();
        eventIdLabel = new Label();
        eventIdTextBox = new TextBox();
        hostTokenLabel = new Label();
        hostTokenTextBox = new TextBox();
        createEventButton = new Button();
        connectButton = new Button();
        statusLabel = new Label();
        operationMessagePanel = new Panel();
        joinGroupBox = new GroupBox();
        joinTableLayoutPanel = new TableLayoutPanel();
        eventInfoValueLabel = new Label();
        joinUrlTextBox = new TextBox();
        copyJoinUrlButton = new Button();
        joinUrlWarningLabel = new Label();
        joinQrCodePictureBox = new PictureBox();
        participantsGroupBox = new GroupBox();
        participantGrid = new DataGridView();
        setupGroupBox.SuspendLayout();
        setupTableLayoutPanel.SuspendLayout();
        operationMessagePanel.SuspendLayout();
        joinGroupBox.SuspendLayout();
        joinTableLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)joinQrCodePictureBox).BeginInit();
        participantsGroupBox.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)participantGrid).BeginInit();
        SuspendLayout();
        titleLabel.Name = "titleLabel";
        setupGroupBox.Name = "setupGroupBox";
        setupTableLayoutPanel.Name = "setupTableLayoutPanel";
        lanAddressLabel.Name = "lanAddressLabel";
        lanAddressComboBox.Name = "lanAddressComboBox";
        refreshLanAddressesButton.Name = "refreshLanAddressesButton";
        testConnectionButton.Name = "testConnectionButton";
        serverUrlLabel.Name = "serverUrlLabel";
        serverUrlTextBox.Name = "serverUrlTextBox";
        installFirewallRuleButton.Name = "installFirewallRuleButton";
        eventNameLabel.Name = "eventNameLabel";
        eventNameTextBox.Name = "eventNameTextBox";
        eventDateLabel.Name = "eventDateLabel";
        eventDatePicker.Name = "eventDatePicker";
        eventIdLabel.Name = "eventIdLabel";
        eventIdTextBox.Name = "eventIdTextBox";
        hostTokenLabel.Name = "hostTokenLabel";
        hostTokenTextBox.Name = "hostTokenTextBox";
        createEventButton.Name = "createEventButton";
        connectButton.Name = "connectButton";
        statusLabel.Name = "statusLabel";
        joinGroupBox.Name = "joinGroupBox";
        joinTableLayoutPanel.Name = "joinTableLayoutPanel";
        eventInfoValueLabel.Name = "eventInfoValueLabel";
        joinUrlTextBox.Name = "joinUrlTextBox";
        copyJoinUrlButton.Name = "copyJoinUrlButton";
        joinUrlWarningLabel.Name = "joinUrlWarningLabel";
        joinQrCodePictureBox.Name = "joinQrCodePictureBox";
        participantsGroupBox.Name = "participantsGroupBox";
        participantGrid.Name = "participantGrid";
        titleLabel.Dock = DockStyle.Top;
        titleLabel.Font = new Font("Microsoft JhengHei UI", 20F, FontStyle.Bold);
        titleLabel.Height = 48;
        titleLabel.Text = "活動與參與者";
        setupGroupBox.Controls.Add(setupTableLayoutPanel);
        setupGroupBox.Dock = DockStyle.Top;
        setupGroupBox.Height = 205;
        setupGroupBox.Text = "活動電腦與連線";
        setupTableLayoutPanel.ColumnCount = 4;
        setupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        setupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        setupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 95F));
        setupTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        setupTableLayoutPanel.Controls.Add(lanAddressLabel, 0, 0);
        setupTableLayoutPanel.Controls.Add(lanAddressComboBox, 1, 0);
        setupTableLayoutPanel.Controls.Add(refreshLanAddressesButton, 2, 0);
        setupTableLayoutPanel.Controls.Add(testConnectionButton, 3, 0);
        setupTableLayoutPanel.Controls.Add(serverUrlLabel, 0, 1);
        setupTableLayoutPanel.Controls.Add(serverUrlTextBox, 1, 1);
        setupTableLayoutPanel.Controls.Add(installFirewallRuleButton, 3, 1);
        setupTableLayoutPanel.Controls.Add(eventNameLabel, 0, 2);
        setupTableLayoutPanel.Controls.Add(eventNameTextBox, 1, 2);
        setupTableLayoutPanel.Controls.Add(eventDateLabel, 2, 2);
        setupTableLayoutPanel.Controls.Add(eventDatePicker, 3, 2);
        setupTableLayoutPanel.Controls.Add(eventIdLabel, 0, 3);
        setupTableLayoutPanel.Controls.Add(eventIdTextBox, 1, 3);
        setupTableLayoutPanel.Controls.Add(hostTokenLabel, 2, 3);
        setupTableLayoutPanel.Controls.Add(hostTokenTextBox, 3, 3);
        setupTableLayoutPanel.Controls.Add(createEventButton, 1, 4);
        setupTableLayoutPanel.Controls.Add(connectButton, 3, 4);
        setupTableLayoutPanel.Dock = DockStyle.Fill;
        setupTableLayoutPanel.Padding = new Padding(12);
        setupTableLayoutPanel.RowCount = 5;
        setupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        setupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        setupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        setupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        setupTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
        lanAddressLabel.Text = "LAN 網卡 / IP";
        lanAddressLabel.TextAlign = ContentAlignment.MiddleLeft;
        lanAddressComboBox.Dock = DockStyle.Fill;
        lanAddressComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        refreshLanAddressesButton.Dock = DockStyle.Fill;
        refreshLanAddressesButton.Text = "重新掃描";
        refreshLanAddressesButton.Click += refreshLanAddressesButton_Click;
        testConnectionButton.Dock = DockStyle.Fill;
        testConnectionButton.Text = "連線檢查";
        testConnectionButton.Click += testConnectionButton_Click;
        serverUrlLabel.Text = "本機 Server";
        serverUrlLabel.TextAlign = ContentAlignment.MiddleLeft;
        serverUrlTextBox.Dock = DockStyle.Fill;
        serverUrlTextBox.Text = "http://localhost:5000";
        setupTableLayoutPanel.SetColumnSpan(serverUrlTextBox, 2);
        installFirewallRuleButton.Dock = DockStyle.Fill;
        installFirewallRuleButton.Text = "建立 Firewall Rule";
        installFirewallRuleButton.Click += installFirewallRuleButton_Click;
        eventNameLabel.Text = "活動名稱";
        eventNameLabel.TextAlign = ContentAlignment.MiddleLeft;
        eventNameTextBox.Dock = DockStyle.Fill;
        eventNameTextBox.Text = "公司活動";
        eventDateLabel.Text = "活動日期";
        eventDateLabel.TextAlign = ContentAlignment.MiddleLeft;
        eventDatePicker.CustomFormat = "yyyy/MM/dd HH:mm";
        eventDatePicker.Dock = DockStyle.Fill;
        eventDatePicker.Format = DateTimePickerFormat.Custom;
        eventIdLabel.Text = "活動 ID";
        eventIdLabel.TextAlign = ContentAlignment.MiddleLeft;
        eventIdTextBox.Dock = DockStyle.Fill;
        hostTokenLabel.Text = "Host Token";
        hostTokenLabel.TextAlign = ContentAlignment.MiddleLeft;
        hostTokenTextBox.Dock = DockStyle.Fill;
        hostTokenTextBox.PasswordChar = '●';
        createEventButton.Dock = DockStyle.Fill;
        createEventButton.Text = "建立活動";
        createEventButton.Click += createEventButton_Click;
        connectButton.Dock = DockStyle.Fill;
        connectButton.Text = "連線既有活動";
        connectButton.Click += connectButton_Click;
        operationMessagePanel.BackColor = Color.FromArgb(241, 248, 245);
        operationMessagePanel.Controls.Add(statusLabel);
        operationMessagePanel.Dock = DockStyle.Top;
        operationMessagePanel.Height = 50;
        operationMessagePanel.Name = "operationMessagePanel";
        operationMessagePanel.Padding = new Padding(12, 8, 12, 8);
        statusLabel.AutoEllipsis = false;
        statusLabel.AutoSize = false;
        statusLabel.Dock = DockStyle.Fill;
        statusLabel.Text = "尚未連線";
        statusLabel.TextAlign = ContentAlignment.MiddleLeft;
        joinGroupBox.Controls.Add(joinTableLayoutPanel);
        joinGroupBox.Dock = DockStyle.Top;
        joinGroupBox.Height = 185;
        joinGroupBox.Text = "加入資訊";
        joinTableLayoutPanel.ColumnCount = 2;
        joinTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 72F));
        joinTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 28F));
        joinTableLayoutPanel.Controls.Add(eventInfoValueLabel, 0, 0);
        joinTableLayoutPanel.Controls.Add(joinUrlTextBox, 0, 1);
        joinTableLayoutPanel.Controls.Add(copyJoinUrlButton, 0, 2);
        joinTableLayoutPanel.Controls.Add(joinUrlWarningLabel, 0, 3);
        joinTableLayoutPanel.Controls.Add(joinQrCodePictureBox, 1, 0);
        joinTableLayoutPanel.SetRowSpan(joinQrCodePictureBox, 4);
        joinTableLayoutPanel.Dock = DockStyle.Fill;
        joinTableLayoutPanel.Padding = new Padding(12);
        joinTableLayoutPanel.RowCount = 4;
        joinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        joinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        joinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
        joinTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        eventInfoValueLabel.Dock = DockStyle.Fill;
        eventInfoValueLabel.Font = new Font("Microsoft JhengHei UI", 12F, FontStyle.Bold);
        eventInfoValueLabel.Text = "尚未建立或連線";
        joinUrlTextBox.Dock = DockStyle.Fill;
        joinUrlTextBox.ReadOnly = true;
        copyJoinUrlButton.Anchor = AnchorStyles.Left;
        copyJoinUrlButton.Size = new Size(110, 30);
        copyJoinUrlButton.Text = "複製加入網址";
        copyJoinUrlButton.Click += copyJoinUrlButton_Click;
        joinUrlWarningLabel.Dock = DockStyle.Fill;
        joinUrlWarningLabel.Text = "建立活動後顯示 QR Code。";
        joinQrCodePictureBox.Dock = DockStyle.Fill;
        joinQrCodePictureBox.SizeMode = PictureBoxSizeMode.Zoom;
        participantsGroupBox.Controls.Add(participantGrid);
        participantsGroupBox.Dock = DockStyle.Fill;
        participantsGroupBox.Text = "參與者";
        participantGrid.AllowUserToAddRows = false;
        participantGrid.AllowUserToDeleteRows = false;
        participantGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        participantGrid.Columns.AddRange(
            new DataGridViewTextBoxColumn { HeaderText = "顯示名稱" },
            new DataGridViewTextBoxColumn { HeaderText = "員工編號" },
            new DataGridViewTextBoxColumn { HeaderText = "部門" },
            new DataGridViewTextBoxColumn { HeaderText = "桌次" },
            new DataGridViewTextBoxColumn { HeaderText = "狀態" },
            new DataGridViewTextBoxColumn { HeaderText = "分數" });
        participantGrid.Dock = DockStyle.Fill;
        participantGrid.ReadOnly = true;
        participantGrid.RowHeadersVisible = false;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(0, 570);
        BackColor = Color.White;
        Controls.Add(participantsGroupBox);
        Controls.Add(joinGroupBox);
        Controls.Add(operationMessagePanel);
        Controls.Add(setupGroupBox);
        Controls.Add(titleLabel);
        Name = "EventManagementView";
        Padding = new Padding(16);
        Size = new Size(984, 728);
        setupGroupBox.ResumeLayout(false);
        setupTableLayoutPanel.ResumeLayout(false);
        setupTableLayoutPanel.PerformLayout();
        operationMessagePanel.ResumeLayout(false);
        joinGroupBox.ResumeLayout(false);
        joinTableLayoutPanel.ResumeLayout(false);
        joinTableLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)joinQrCodePictureBox).EndInit();
        participantsGroupBox.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)participantGrid).EndInit();
        ResumeLayout(false);
    }

    private Label titleLabel;
    private GroupBox setupGroupBox;
    private TableLayoutPanel setupTableLayoutPanel;
    private Label lanAddressLabel;
    private ComboBox lanAddressComboBox;
    private Button refreshLanAddressesButton;
    private Button testConnectionButton;
    private Label serverUrlLabel;
    private TextBox serverUrlTextBox;
    private Button installFirewallRuleButton;
    private Label eventNameLabel;
    private TextBox eventNameTextBox;
    private Label eventDateLabel;
    private DateTimePicker eventDatePicker;
    private Label eventIdLabel;
    private TextBox eventIdTextBox;
    private Label hostTokenLabel;
    private TextBox hostTokenTextBox;
    private Button createEventButton;
    private Button connectButton;
    private Label statusLabel;
    private Panel operationMessagePanel;
    private GroupBox joinGroupBox;
    private TableLayoutPanel joinTableLayoutPanel;
    private Label eventInfoValueLabel;
    private TextBox joinUrlTextBox;
    private Button copyJoinUrlButton;
    private Label joinUrlWarningLabel;
    private PictureBox joinQrCodePictureBox;
    private GroupBox participantsGroupBox;
    private DataGridView participantGrid;
}
