#nullable disable

namespace EventHub.Host.Views;

partial class LiveMonitorView
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayoutPanel = new TableLayoutPanel();
        titleLabel = new Label();
        statusTableLayoutPanel = new TableLayoutPanel();
        activityCaptionLabel = new Label();
        activityValueLabel = new Label();
        questionCaptionLabel = new Label();
        questionValueLabel = new Label();
        modeCaptionLabel = new Label();
        modeValueLabel = new Label();
        stateCaptionLabel = new Label();
        stateValueLabel = new Label();
        timeCaptionLabel = new Label();
        timeValueLabel = new Label();
        answeredCaptionLabel = new Label();
        answeredValueLabel = new Label();
        onlineCaptionLabel = new Label();
        onlineValueLabel = new Label();
        displayGroupBox = new GroupBox();
        displayLayoutPanel = new TableLayoutPanel();
        displayModeValueLabel = new Label();
        displayButtonsLayoutPanel = new TableLayoutPanel();
        waitingButton = new Button();
        liveButton = new Button();
        resultButton = new Button();
        rankingButton = new Button();
        displayStatusLabel = new Label();
        countdownTimer = new System.Windows.Forms.Timer(components);
        rootLayoutPanel.SuspendLayout();
        statusTableLayoutPanel.SuspendLayout();
        displayGroupBox.SuspendLayout();
        displayLayoutPanel.SuspendLayout();
        displayButtonsLayoutPanel.SuspendLayout();
        SuspendLayout();
        rootLayoutPanel.ColumnCount = 1;
        rootLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayoutPanel.Controls.Add(titleLabel, 0, 0);
        rootLayoutPanel.Controls.Add(statusTableLayoutPanel, 0, 1);
        rootLayoutPanel.Controls.Add(displayGroupBox, 0, 2);
        rootLayoutPanel.Dock = DockStyle.Fill;
        rootLayoutPanel.Name = "rootLayoutPanel";
        rootLayoutPanel.Padding = new Padding(12);
        rootLayoutPanel.RowCount = 3;
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 52F));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 48F));
        titleLabel.Dock = DockStyle.Fill;
        titleLabel.Font = new Font("Microsoft JhengHei UI", 16F, FontStyle.Bold);
        titleLabel.Name = "titleLabel";
        titleLabel.Text = "LIVE MONITOR";
        titleLabel.TextAlign = ContentAlignment.MiddleLeft;
        statusTableLayoutPanel.ColumnCount = 2;
        statusTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F));
        statusTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F));
        statusTableLayoutPanel.Controls.Add(activityCaptionLabel, 0, 0);
        statusTableLayoutPanel.Controls.Add(activityValueLabel, 1, 0);
        statusTableLayoutPanel.Controls.Add(questionCaptionLabel, 0, 1);
        statusTableLayoutPanel.Controls.Add(questionValueLabel, 1, 1);
        statusTableLayoutPanel.Controls.Add(modeCaptionLabel, 0, 2);
        statusTableLayoutPanel.Controls.Add(modeValueLabel, 1, 2);
        statusTableLayoutPanel.Controls.Add(stateCaptionLabel, 0, 3);
        statusTableLayoutPanel.Controls.Add(stateValueLabel, 1, 3);
        statusTableLayoutPanel.Controls.Add(timeCaptionLabel, 0, 4);
        statusTableLayoutPanel.Controls.Add(timeValueLabel, 1, 4);
        statusTableLayoutPanel.Controls.Add(answeredCaptionLabel, 0, 5);
        statusTableLayoutPanel.Controls.Add(answeredValueLabel, 1, 5);
        statusTableLayoutPanel.Controls.Add(onlineCaptionLabel, 0, 6);
        statusTableLayoutPanel.Controls.Add(onlineValueLabel, 1, 6);
        statusTableLayoutPanel.Dock = DockStyle.Fill;
        statusTableLayoutPanel.Name = "statusTableLayoutPanel";
        statusTableLayoutPanel.RowCount = 7;
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        statusTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 14.28571F));
        activityCaptionLabel.Dock = DockStyle.Fill;
        activityCaptionLabel.Name = "activityCaptionLabel";
        activityCaptionLabel.Text = "Activity";
        activityValueLabel.Dock = DockStyle.Fill;
        activityValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        activityValueLabel.Name = "activityValueLabel";
        activityValueLabel.Text = "Quiz";
        questionCaptionLabel.Dock = DockStyle.Fill;
        questionCaptionLabel.Name = "questionCaptionLabel";
        questionCaptionLabel.Text = "Question";
        questionValueLabel.Dock = DockStyle.Fill;
        questionValueLabel.Name = "questionValueLabel";
        questionValueLabel.Text = "— / —";
        modeCaptionLabel.Dock = DockStyle.Fill;
        modeCaptionLabel.Name = "modeCaptionLabel";
        modeCaptionLabel.Text = "Mode";
        modeValueLabel.Dock = DockStyle.Fill;
        modeValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        modeValueLabel.Name = "modeValueLabel";
        modeValueLabel.Text = "—";
        stateCaptionLabel.Dock = DockStyle.Fill;
        stateCaptionLabel.Name = "stateCaptionLabel";
        stateCaptionLabel.Text = "State";
        stateValueLabel.Dock = DockStyle.Fill;
        stateValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        stateValueLabel.Name = "stateValueLabel";
        stateValueLabel.Text = "WAITING";
        timeCaptionLabel.Dock = DockStyle.Fill;
        timeCaptionLabel.Name = "timeCaptionLabel";
        timeCaptionLabel.Text = "Time";
        timeValueLabel.Dock = DockStyle.Fill;
        timeValueLabel.Font = new Font("Consolas", 15F, FontStyle.Bold);
        timeValueLabel.Name = "timeValueLabel";
        timeValueLabel.Text = "--:--";
        answeredCaptionLabel.Dock = DockStyle.Fill;
        answeredCaptionLabel.Name = "answeredCaptionLabel";
        answeredCaptionLabel.Text = "Answered";
        answeredValueLabel.Dock = DockStyle.Fill;
        answeredValueLabel.Name = "answeredValueLabel";
        answeredValueLabel.Text = "0 / 0";
        onlineCaptionLabel.Dock = DockStyle.Fill;
        onlineCaptionLabel.Name = "onlineCaptionLabel";
        onlineCaptionLabel.Text = "Online";
        onlineValueLabel.Dock = DockStyle.Fill;
        onlineValueLabel.Name = "onlineValueLabel";
        onlineValueLabel.Text = "0";
        displayGroupBox.Controls.Add(displayLayoutPanel);
        displayGroupBox.Dock = DockStyle.Fill;
        displayGroupBox.Name = "displayGroupBox";
        displayGroupBox.Text = "DISPLAY OVERRIDE";
        displayLayoutPanel.ColumnCount = 1;
        displayLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        displayLayoutPanel.Controls.Add(displayModeValueLabel, 0, 0);
        displayLayoutPanel.Controls.Add(displayButtonsLayoutPanel, 0, 1);
        displayLayoutPanel.Controls.Add(displayStatusLabel, 0, 2);
        displayLayoutPanel.Dock = DockStyle.Fill;
        displayLayoutPanel.Name = "displayLayoutPanel";
        displayLayoutPanel.RowCount = 3;
        displayLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 54F));
        displayLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        displayLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        displayModeValueLabel.Dock = DockStyle.Fill;
        displayModeValueLabel.Font = new Font("Microsoft JhengHei UI", 20F, FontStyle.Bold);
        displayModeValueLabel.ForeColor = Color.FromArgb(24, 86, 138);
        displayModeValueLabel.Name = "displayModeValueLabel";
        displayModeValueLabel.Text = "WAITING";
        displayModeValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        displayButtonsLayoutPanel.ColumnCount = 2;
        displayButtonsLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        displayButtonsLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        displayButtonsLayoutPanel.Controls.Add(waitingButton, 0, 0);
        displayButtonsLayoutPanel.Controls.Add(liveButton, 1, 0);
        displayButtonsLayoutPanel.Controls.Add(resultButton, 0, 1);
        displayButtonsLayoutPanel.Controls.Add(rankingButton, 1, 1);
        displayButtonsLayoutPanel.Dock = DockStyle.Fill;
        displayButtonsLayoutPanel.Name = "displayButtonsLayoutPanel";
        displayButtonsLayoutPanel.RowCount = 2;
        displayButtonsLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        displayButtonsLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        waitingButton.Dock = DockStyle.Fill;
        waitingButton.Margin = new Padding(4);
        waitingButton.Name = "waitingButton";
        waitingButton.Text = "Waiting";
        waitingButton.Click += waitingButton_Click;
        liveButton.Dock = DockStyle.Fill;
        liveButton.Margin = new Padding(4);
        liveButton.Name = "liveButton";
        liveButton.Text = "Live";
        liveButton.Click += liveButton_Click;
        resultButton.Dock = DockStyle.Fill;
        resultButton.Margin = new Padding(4);
        resultButton.Name = "resultButton";
        resultButton.Text = "Result";
        resultButton.Click += resultButton_Click;
        rankingButton.Dock = DockStyle.Fill;
        rankingButton.Margin = new Padding(4);
        rankingButton.Name = "rankingButton";
        rankingButton.Text = "Ranking";
        rankingButton.Click += rankingButton_Click;
        displayStatusLabel.Dock = DockStyle.Fill;
        displayStatusLabel.Name = "displayStatusLabel";
        displayStatusLabel.Text = "等待操作";
        displayStatusLabel.TextAlign = ContentAlignment.MiddleCenter;
        countdownTimer.Interval = 250;
        countdownTimer.Tick += countdownTimer_Tick;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.WhiteSmoke;
        Controls.Add(rootLayoutPanel);
        Name = "LiveMonitorView";
        Size = new Size(270, 680);
        rootLayoutPanel.ResumeLayout(false);
        statusTableLayoutPanel.ResumeLayout(false);
        displayGroupBox.ResumeLayout(false);
        displayLayoutPanel.ResumeLayout(false);
        displayButtonsLayoutPanel.ResumeLayout(false);
        ResumeLayout(false);
    }

    private TableLayoutPanel rootLayoutPanel;
    private Label titleLabel;
    private TableLayoutPanel statusTableLayoutPanel;
    private Label activityCaptionLabel;
    private Label activityValueLabel;
    private Label questionCaptionLabel;
    private Label questionValueLabel;
    private Label modeCaptionLabel;
    private Label modeValueLabel;
    private Label stateCaptionLabel;
    private Label stateValueLabel;
    private Label timeCaptionLabel;
    private Label timeValueLabel;
    private Label answeredCaptionLabel;
    private Label answeredValueLabel;
    private Label onlineCaptionLabel;
    private Label onlineValueLabel;
    private GroupBox displayGroupBox;
    private TableLayoutPanel displayLayoutPanel;
    private Label displayModeValueLabel;
    private TableLayoutPanel displayButtonsLayoutPanel;
    private Button waitingButton;
    private Button liveButton;
    private Button resultButton;
    private Button rankingButton;
    private Label displayStatusLabel;
    private System.Windows.Forms.Timer countdownTimer;
}
