#nullable disable

namespace EventHub.Host.Views;

partial class QuizControlView
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        titleLabel = new Label();
        contextTableLayoutPanel = new TableLayoutPanel();
        quizTitleCaptionLabel = new Label();
        quizTitleValueLabel = new Label();
        questionPositionCaptionLabel = new Label();
        questionPositionLabel = new Label();
        questionStateCaptionLabel = new Label();
        questionStateValueLabel = new Label();
        progressValueLabel = new Label();
        countdownCaptionLabel = new Label();
        countdownValueLabel = new Label();
        questionGroupBox = new GroupBox();
        questionLayoutPanel = new TableLayoutPanel();
        questionTextLabel = new Label();
        optionALabel = new Label();
        optionBLabel = new Label();
        optionCLabel = new Label();
        optionDLabel = new Label();
        primaryActionPanel = new Panel();
        guidanceLabel = new Label();
        primaryActionButton = new Button();
        statusLabel = new Label();
        manualQuestionGroupBox = new GroupBox();
        manualLayoutPanel = new TableLayoutPanel();
        manualQuestionTextBox = new TextBox();
        manualOptionATextBox = new TextBox();
        manualOptionBTextBox = new TextBox();
        manualOptionCTextBox = new TextBox();
        manualOptionDTextBox = new TextBox();
        manualCorrectOptionComboBox = new ComboBox();
        manualDurationNumeric = new NumericUpDown();
        createManualQuestionButton = new Button();
        countdownTimer = new System.Windows.Forms.Timer(components);
        contextTableLayoutPanel.SuspendLayout();
        questionGroupBox.SuspendLayout();
        questionLayoutPanel.SuspendLayout();
        primaryActionPanel.SuspendLayout();
        manualQuestionGroupBox.SuspendLayout();
        manualLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)manualDurationNumeric).BeginInit();
        SuspendLayout();
        titleLabel.Name = "titleLabel";
        contextTableLayoutPanel.Name = "contextTableLayoutPanel";
        quizTitleCaptionLabel.Name = "quizTitleCaptionLabel";
        quizTitleValueLabel.Name = "quizTitleValueLabel";
        questionPositionCaptionLabel.Name = "questionPositionCaptionLabel";
        questionPositionLabel.Name = "questionPositionLabel";
        questionStateCaptionLabel.Name = "questionStateCaptionLabel";
        questionStateValueLabel.Name = "questionStateValueLabel";
        progressValueLabel.Name = "progressValueLabel";
        countdownCaptionLabel.Name = "countdownCaptionLabel";
        countdownValueLabel.Name = "countdownValueLabel";
        questionGroupBox.Name = "questionGroupBox";
        questionLayoutPanel.Name = "questionLayoutPanel";
        questionTextLabel.Name = "questionTextLabel";
        optionALabel.Name = "optionALabel";
        optionBLabel.Name = "optionBLabel";
        optionCLabel.Name = "optionCLabel";
        optionDLabel.Name = "optionDLabel";
        primaryActionPanel.Name = "primaryActionPanel";
        guidanceLabel.Name = "guidanceLabel";
        primaryActionButton.Name = "primaryActionButton";
        statusLabel.Name = "statusLabel";
        manualQuestionGroupBox.Name = "manualQuestionGroupBox";
        manualLayoutPanel.Name = "manualLayoutPanel";
        manualQuestionTextBox.Name = "manualQuestionTextBox";
        manualOptionATextBox.Name = "manualOptionATextBox";
        manualOptionBTextBox.Name = "manualOptionBTextBox";
        manualOptionCTextBox.Name = "manualOptionCTextBox";
        manualOptionDTextBox.Name = "manualOptionDTextBox";
        manualCorrectOptionComboBox.Name = "manualCorrectOptionComboBox";
        manualDurationNumeric.Name = "manualDurationNumeric";
        createManualQuestionButton.Name = "createManualQuestionButton";
        titleLabel.Dock = DockStyle.Top;
        titleLabel.Font = new Font("Microsoft JhengHei UI", 20F, FontStyle.Bold);
        titleLabel.Height = 58;
        titleLabel.Text = "Quiz 現場控制";
        contextTableLayoutPanel.ColumnCount = 6;
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45F));
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
        contextTableLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 35F));
        contextTableLayoutPanel.Controls.Add(quizTitleCaptionLabel, 0, 0);
        contextTableLayoutPanel.Controls.Add(quizTitleValueLabel, 1, 0);
        contextTableLayoutPanel.Controls.Add(questionPositionCaptionLabel, 2, 0);
        contextTableLayoutPanel.Controls.Add(questionPositionLabel, 3, 0);
        contextTableLayoutPanel.Controls.Add(questionStateCaptionLabel, 0, 1);
        contextTableLayoutPanel.Controls.Add(questionStateValueLabel, 1, 1);
        contextTableLayoutPanel.Controls.Add(progressValueLabel, 2, 1);
        contextTableLayoutPanel.SetColumnSpan(progressValueLabel, 4);
        contextTableLayoutPanel.Controls.Add(countdownCaptionLabel, 4, 0);
        contextTableLayoutPanel.Controls.Add(countdownValueLabel, 5, 0);
        contextTableLayoutPanel.Dock = DockStyle.Top;
        contextTableLayoutPanel.Height = 74;
        contextTableLayoutPanel.RowCount = 2;
        contextTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        contextTableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        quizTitleCaptionLabel.Dock = DockStyle.Fill;
        quizTitleCaptionLabel.Text = "題庫";
        quizTitleValueLabel.AutoEllipsis = true;
        quizTitleValueLabel.Dock = DockStyle.Fill;
        quizTitleValueLabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        quizTitleValueLabel.Text = "尚未選擇";
        questionPositionCaptionLabel.Dock = DockStyle.Fill;
        questionPositionCaptionLabel.Text = "題次";
        questionPositionLabel.Dock = DockStyle.Fill;
        questionPositionLabel.Text = "— / —";
        questionStateCaptionLabel.Dock = DockStyle.Fill;
        questionStateCaptionLabel.Text = "狀態";
        questionStateValueLabel.Dock = DockStyle.Fill;
        questionStateValueLabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        questionStateValueLabel.Text = "Waiting";
        progressValueLabel.Dock = DockStyle.Fill;
        progressValueLabel.Text = "已作答 0 / 0　在線 0";
        countdownCaptionLabel.Dock = DockStyle.Fill;
        countdownCaptionLabel.Text = "倒數";
        countdownValueLabel.Dock = DockStyle.Fill;
        countdownValueLabel.Font = new Font("Consolas", 16F, FontStyle.Bold);
        countdownValueLabel.Text = "--:--";
        questionGroupBox.Controls.Add(questionLayoutPanel);
        questionGroupBox.Dock = DockStyle.Top;
        questionGroupBox.Height = 285;
        questionGroupBox.Text = "目前題目";
        questionLayoutPanel.ColumnCount = 2;
        questionLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        questionLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        questionLayoutPanel.Controls.Add(questionTextLabel, 0, 0);
        questionLayoutPanel.SetColumnSpan(questionTextLabel, 2);
        questionLayoutPanel.Controls.Add(optionALabel, 0, 1);
        questionLayoutPanel.Controls.Add(optionBLabel, 1, 1);
        questionLayoutPanel.Controls.Add(optionCLabel, 0, 2);
        questionLayoutPanel.Controls.Add(optionDLabel, 1, 2);
        questionLayoutPanel.Dock = DockStyle.Fill;
        questionLayoutPanel.Padding = new Padding(16);
        questionLayoutPanel.RowCount = 3;
        questionLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 44F));
        questionLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 28F));
        questionLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 28F));
        questionTextLabel.Dock = DockStyle.Fill;
        questionTextLabel.Font = new Font("Microsoft JhengHei UI", 17F, FontStyle.Bold);
        questionTextLabel.Text = "請先到題庫選擇題目";
        questionTextLabel.TextAlign = ContentAlignment.MiddleCenter;
        ConfigureOption(optionALabel, "A. —");
        ConfigureOption(optionBLabel, "B. —");
        ConfigureOption(optionCLabel, "C. —");
        ConfigureOption(optionDLabel, "D. —");
        primaryActionPanel.Controls.Add(guidanceLabel);
        primaryActionPanel.Controls.Add(primaryActionButton);
        primaryActionPanel.Controls.Add(statusLabel);
        primaryActionPanel.Dock = DockStyle.Top;
        primaryActionPanel.Height = 116;
        guidanceLabel.AutoEllipsis = true;
        guidanceLabel.Font = new Font("Microsoft JhengHei UI", 10F);
        guidanceLabel.Location = new Point(8, 8);
        guidanceLabel.Size = new Size(610, 26);
        guidanceLabel.Text = "請先到題庫選擇題目。";
        primaryActionButton.BackColor = Color.FromArgb(29, 112, 184);
        primaryActionButton.Enabled = false;
        primaryActionButton.FlatStyle = FlatStyle.Flat;
        primaryActionButton.Font = new Font("Microsoft JhengHei UI", 14F, FontStyle.Bold);
        primaryActionButton.ForeColor = Color.White;
        primaryActionButton.Location = new Point(8, 40);
        primaryActionButton.Size = new Size(240, 56);
        primaryActionButton.Text = "等待題目";
        primaryActionButton.Click += primaryActionButton_Click;
        statusLabel.AutoEllipsis = true;
        statusLabel.Location = new Point(270, 55);
        statusLabel.Size = new Size(600, 30);
        statusLabel.Text = "等待操作";
        manualQuestionGroupBox.Controls.Add(manualLayoutPanel);
        manualQuestionGroupBox.Dock = DockStyle.Fill;
        manualQuestionGroupBox.Text = "手動測試建題（Debug / 備用）";
        manualLayoutPanel.ColumnCount = 6;
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 15F));
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 15F));
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 15F));
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 15F));
        manualLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 15F));
        manualLayoutPanel.Controls.Add(manualQuestionTextBox, 0, 0);
        manualLayoutPanel.SetColumnSpan(manualQuestionTextBox, 6);
        manualLayoutPanel.Controls.Add(manualOptionATextBox, 0, 1);
        manualLayoutPanel.Controls.Add(manualOptionBTextBox, 1, 1);
        manualLayoutPanel.Controls.Add(manualOptionCTextBox, 2, 1);
        manualLayoutPanel.Controls.Add(manualOptionDTextBox, 3, 1);
        manualLayoutPanel.Controls.Add(manualCorrectOptionComboBox, 4, 1);
        manualLayoutPanel.Controls.Add(manualDurationNumeric, 5, 1);
        manualLayoutPanel.Controls.Add(createManualQuestionButton, 5, 2);
        manualLayoutPanel.Dock = DockStyle.Fill;
        manualLayoutPanel.Padding = new Padding(12);
        manualLayoutPanel.RowCount = 3;
        manualLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        manualLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        manualLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        manualQuestionTextBox.Dock = DockStyle.Fill;
        manualQuestionTextBox.Text = "1 + 1 = ?";
        manualOptionATextBox.Dock = DockStyle.Fill;
        manualOptionATextBox.Text = "1";
        manualOptionBTextBox.Dock = DockStyle.Fill;
        manualOptionBTextBox.Text = "2";
        manualOptionCTextBox.Dock = DockStyle.Fill;
        manualOptionCTextBox.Text = "3";
        manualOptionDTextBox.Dock = DockStyle.Fill;
        manualOptionDTextBox.Text = "4";
        manualCorrectOptionComboBox.Dock = DockStyle.Fill;
        manualCorrectOptionComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
        manualCorrectOptionComboBox.Items.AddRange(new object[] { "A", "B", "C", "D" });
        manualCorrectOptionComboBox.SelectedIndex = 1;
        manualDurationNumeric.Dock = DockStyle.Fill;
        manualDurationNumeric.Maximum = 300;
        manualDurationNumeric.Minimum = 3;
        manualDurationNumeric.Value = 20;
        createManualQuestionButton.Dock = DockStyle.Fill;
        createManualQuestionButton.Text = "建立題目";
        createManualQuestionButton.Click += createManualQuestionButton_Click;
        countdownTimer.Enabled = true;
        countdownTimer.Interval = 250;
        countdownTimer.Tick += countdownTimer_Tick;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.White;
        Controls.Add(manualQuestionGroupBox);
        Controls.Add(primaryActionPanel);
        Controls.Add(questionGroupBox);
        Controls.Add(contextTableLayoutPanel);
        Controls.Add(titleLabel);
        Name = "QuizControlView";
        Padding = new Padding(24);
        Size = new Size(984, 728);
        contextTableLayoutPanel.ResumeLayout(false);
        questionGroupBox.ResumeLayout(false);
        questionLayoutPanel.ResumeLayout(false);
        primaryActionPanel.ResumeLayout(false);
        manualQuestionGroupBox.ResumeLayout(false);
        manualLayoutPanel.ResumeLayout(false);
        manualLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)manualDurationNumeric).EndInit();
        ResumeLayout(false);
    }

    private static void ConfigureOption(Label label, string text)
    {
        label.AutoEllipsis = true;
        label.Dock = DockStyle.Fill;
        label.Font = new Font("Microsoft JhengHei UI", 12F, FontStyle.Bold);
        label.Margin = new Padding(6);
        label.Padding = new Padding(12);
        label.Text = text;
        label.TextAlign = ContentAlignment.MiddleLeft;
    }

    private Label titleLabel;
    private TableLayoutPanel contextTableLayoutPanel;
    private Label quizTitleCaptionLabel;
    private Label quizTitleValueLabel;
    private Label questionPositionCaptionLabel;
    private Label questionPositionLabel;
    private Label questionStateCaptionLabel;
    private Label questionStateValueLabel;
    private Label progressValueLabel;
    private Label countdownCaptionLabel;
    private Label countdownValueLabel;
    private GroupBox questionGroupBox;
    private TableLayoutPanel questionLayoutPanel;
    private Label questionTextLabel;
    private Label optionALabel;
    private Label optionBLabel;
    private Label optionCLabel;
    private Label optionDLabel;
    private Panel primaryActionPanel;
    private Label guidanceLabel;
    private Button primaryActionButton;
    private Label statusLabel;
    private GroupBox manualQuestionGroupBox;
    private TableLayoutPanel manualLayoutPanel;
    private TextBox manualQuestionTextBox;
    private TextBox manualOptionATextBox;
    private TextBox manualOptionBTextBox;
    private TextBox manualOptionCTextBox;
    private TextBox manualOptionDTextBox;
    private ComboBox manualCorrectOptionComboBox;
    private NumericUpDown manualDurationNumeric;
    private Button createManualQuestionButton;
    private System.Windows.Forms.Timer countdownTimer;
}
