#nullable disable

namespace EventHub.Host.Views;

partial class QuizActivityView
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayoutPanel = new TableLayoutPanel();
        titleLabel = new Label();
        contextLayoutPanel = new TableLayoutPanel();
        quizTitleCaptionLabel = new Label();
        quizTitleValueLabel = new Label();
        modeCaptionLabel = new Label();
        modeValueLabel = new Label();
        questionNumberCaptionLabel = new Label();
        questionNumberValueLabel = new Label();
        stateCaptionLabel = new Label();
        stateValueLabel = new Label();
        progressValueLabel = new Label();
        countdownValueLabel = new Label();
        bodyLayoutPanel = new TableLayoutPanel();
        questionListGroupBox = new GroupBox();
        questionListLayoutPanel = new TableLayoutPanel();
        defaultPracticeButton = new Button();
        questionListGrid = new DataGridView();
        activityTabControl = new TabControl();
        questionTabPage = new TabPage();
        questionContentLayoutPanel = new TableLayoutPanel();
        questionTextLabel = new Label();
        optionsLayoutPanel = new TableLayoutPanel();
        optionALabel = new Label();
        optionBLabel = new Label();
        optionCLabel = new Label();
        optionDLabel = new Label();
        practiceCompletePanel = new Panel();
        practiceCompleteLayoutPanel = new TableLayoutPanel();
        practiceCompleteTitleLabel = new Label();
        practiceCompleteHintLabel = new Label();
        practiceParticipantCaptionLabel = new Label();
        practiceParticipantValueLabel = new Label();
        practiceAnsweredCaptionLabel = new Label();
        practiceAnsweredValueLabel = new Label();
        practiceNotAnsweredCaptionLabel = new Label();
        practiceNotAnsweredValueLabel = new Label();
        resultTabPage = new TabPage();
        resultLayoutPanel = new TableLayoutPanel();
        correctAnswerValueLabel = new Label();
        resultSummaryValueLabel = new Label();
        explanationTextBox = new TextBox();
        distributionGrid = new DataGridView();
        leaderboardTabPage = new TabPage();
        leaderboardGrid = new DataGridView();
        countdownTimer = new System.Windows.Forms.Timer(components);
        rootLayoutPanel.SuspendLayout();
        contextLayoutPanel.SuspendLayout();
        bodyLayoutPanel.SuspendLayout();
        questionListGroupBox.SuspendLayout();
        questionListLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)questionListGrid).BeginInit();
        activityTabControl.SuspendLayout();
        questionTabPage.SuspendLayout();
        questionContentLayoutPanel.SuspendLayout();
        optionsLayoutPanel.SuspendLayout();
        practiceCompletePanel.SuspendLayout();
        practiceCompleteLayoutPanel.SuspendLayout();
        resultTabPage.SuspendLayout();
        resultLayoutPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)distributionGrid).BeginInit();
        leaderboardTabPage.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)leaderboardGrid).BeginInit();
        SuspendLayout();
        rootLayoutPanel.ColumnCount = 1;
        rootLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayoutPanel.Controls.Add(titleLabel, 0, 0);
        rootLayoutPanel.Controls.Add(contextLayoutPanel, 0, 1);
        rootLayoutPanel.Controls.Add(bodyLayoutPanel, 0, 2);
        rootLayoutPanel.Dock = DockStyle.Fill;
        rootLayoutPanel.Name = "rootLayoutPanel";
        rootLayoutPanel.RowCount = 3;
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 52F));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 76F));
        rootLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        titleLabel.Dock = DockStyle.Fill;
        titleLabel.Font = new Font("Microsoft JhengHei UI", 20F, FontStyle.Bold);
        titleLabel.Name = "titleLabel";
        titleLabel.Text = "快問快答｜Live Activity";
        titleLabel.TextAlign = ContentAlignment.MiddleLeft;
        contextLayoutPanel.ColumnCount = 8;
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 28F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 22F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54F));
        contextLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        contextLayoutPanel.Controls.Add(quizTitleCaptionLabel, 0, 0);
        contextLayoutPanel.Controls.Add(quizTitleValueLabel, 1, 0);
        contextLayoutPanel.Controls.Add(modeCaptionLabel, 2, 0);
        contextLayoutPanel.Controls.Add(modeValueLabel, 3, 0);
        contextLayoutPanel.Controls.Add(questionNumberCaptionLabel, 4, 0);
        contextLayoutPanel.Controls.Add(questionNumberValueLabel, 5, 0);
        contextLayoutPanel.Controls.Add(stateCaptionLabel, 6, 0);
        contextLayoutPanel.Controls.Add(stateValueLabel, 7, 0);
        contextLayoutPanel.Controls.Add(progressValueLabel, 0, 1);
        contextLayoutPanel.SetColumnSpan(progressValueLabel, 6);
        contextLayoutPanel.Controls.Add(countdownValueLabel, 6, 1);
        contextLayoutPanel.SetColumnSpan(countdownValueLabel, 2);
        contextLayoutPanel.Dock = DockStyle.Fill;
        contextLayoutPanel.Name = "contextLayoutPanel";
        contextLayoutPanel.RowCount = 2;
        contextLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        contextLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        quizTitleCaptionLabel.Dock = DockStyle.Fill;
        quizTitleCaptionLabel.Name = "quizTitleCaptionLabel";
        quizTitleCaptionLabel.Text = "Quiz";
        quizTitleValueLabel.AutoEllipsis = true;
        quizTitleValueLabel.Dock = DockStyle.Fill;
        quizTitleValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        quizTitleValueLabel.Name = "quizTitleValueLabel";
        quizTitleValueLabel.Text = "尚未選擇";
        modeCaptionLabel.Dock = DockStyle.Fill;
        modeCaptionLabel.Name = "modeCaptionLabel";
        modeCaptionLabel.Text = "Mode";
        modeValueLabel.AutoEllipsis = true;
        modeValueLabel.Dock = DockStyle.Fill;
        modeValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        modeValueLabel.Name = "modeValueLabel";
        modeValueLabel.Text = "—";
        questionNumberCaptionLabel.Dock = DockStyle.Fill;
        questionNumberCaptionLabel.Name = "questionNumberCaptionLabel";
        questionNumberCaptionLabel.Text = "題次";
        questionNumberValueLabel.Dock = DockStyle.Fill;
        questionNumberValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        questionNumberValueLabel.Name = "questionNumberValueLabel";
        questionNumberValueLabel.Text = "— / —";
        stateCaptionLabel.Dock = DockStyle.Fill;
        stateCaptionLabel.Name = "stateCaptionLabel";
        stateCaptionLabel.Text = "State";
        stateValueLabel.Dock = DockStyle.Fill;
        stateValueLabel.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold);
        stateValueLabel.Name = "stateValueLabel";
        stateValueLabel.Text = "WAITING";
        progressValueLabel.Dock = DockStyle.Fill;
        progressValueLabel.Name = "progressValueLabel";
        progressValueLabel.Text = "已作答 0 / 0　在線 0";
        countdownValueLabel.Dock = DockStyle.Fill;
        countdownValueLabel.Font = new Font("Consolas", 17F, FontStyle.Bold);
        countdownValueLabel.Name = "countdownValueLabel";
        countdownValueLabel.Text = "--:--";
        countdownValueLabel.TextAlign = ContentAlignment.MiddleRight;
        bodyLayoutPanel.ColumnCount = 2;
        bodyLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 230F));
        bodyLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        bodyLayoutPanel.Controls.Add(questionListGroupBox, 0, 0);
        bodyLayoutPanel.Controls.Add(activityTabControl, 1, 0);
        bodyLayoutPanel.Dock = DockStyle.Fill;
        bodyLayoutPanel.Name = "bodyLayoutPanel";
        bodyLayoutPanel.RowCount = 1;
        bodyLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        questionListGroupBox.Controls.Add(questionListLayoutPanel);
        questionListGroupBox.Dock = DockStyle.Fill;
        questionListGroupBox.Name = "questionListGroupBox";
        questionListGroupBox.Text = "題目流程";
        questionListLayoutPanel.ColumnCount = 1;
        questionListLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        questionListLayoutPanel.Controls.Add(defaultPracticeButton, 0, 0);
        questionListLayoutPanel.Controls.Add(questionListGrid, 0, 1);
        questionListLayoutPanel.Dock = DockStyle.Fill;
        questionListLayoutPanel.Name = "questionListLayoutPanel";
        questionListLayoutPanel.RowCount = 2;
        questionListLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        questionListLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        defaultPracticeButton.Dock = DockStyle.Fill;
        defaultPracticeButton.Margin = new Padding(6);
        defaultPracticeButton.Name = "defaultPracticeButton";
        defaultPracticeButton.Text = "執行內建熱身";
        defaultPracticeButton.Click += defaultPracticeButton_Click;
        questionListGrid.AllowUserToAddRows = false;
        questionListGrid.AllowUserToDeleteRows = false;
        questionListGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        questionListGrid.Columns.AddRange(
            new DataGridViewTextBoxColumn { HeaderText = "題次", FillWeight = 35 },
            new DataGridViewTextBoxColumn { HeaderText = "狀態", FillWeight = 25 },
            new DataGridViewTextBoxColumn { HeaderText = "題目", FillWeight = 100 });
        questionListGrid.Dock = DockStyle.Fill;
        questionListGrid.MultiSelect = false;
        questionListGrid.Name = "questionListGrid";
        questionListGrid.ReadOnly = true;
        questionListGrid.RowHeadersVisible = false;
        questionListGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        questionListGrid.SelectionChanged += questionListGrid_SelectionChanged;
        activityTabControl.Controls.Add(questionTabPage);
        activityTabControl.Controls.Add(resultTabPage);
        activityTabControl.Controls.Add(leaderboardTabPage);
        activityTabControl.Dock = DockStyle.Fill;
        activityTabControl.Name = "activityTabControl";
        questionTabPage.Controls.Add(practiceCompletePanel);
        questionTabPage.Controls.Add(questionContentLayoutPanel);
        questionTabPage.Name = "questionTabPage";
        questionTabPage.Text = "題目";
        questionContentLayoutPanel.ColumnCount = 1;
        questionContentLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        questionContentLayoutPanel.Controls.Add(questionTextLabel, 0, 0);
        questionContentLayoutPanel.Controls.Add(optionsLayoutPanel, 0, 1);
        questionContentLayoutPanel.Dock = DockStyle.Fill;
        questionContentLayoutPanel.Name = "questionContentLayoutPanel";
        questionContentLayoutPanel.Padding = new Padding(12);
        questionContentLayoutPanel.RowCount = 2;
        questionContentLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 36F));
        questionContentLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 64F));
        questionTextLabel.Dock = DockStyle.Fill;
        questionTextLabel.Font = new Font("Microsoft JhengHei UI", 16F, FontStyle.Bold);
        questionTextLabel.Name = "questionTextLabel";
        questionTextLabel.Padding = new Padding(10);
        questionTextLabel.Text = "請先選擇題目";
        questionTextLabel.TextAlign = ContentAlignment.MiddleCenter;
        optionsLayoutPanel.ColumnCount = 2;
        optionsLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        optionsLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        optionsLayoutPanel.Controls.Add(optionALabel, 0, 0);
        optionsLayoutPanel.Controls.Add(optionBLabel, 1, 0);
        optionsLayoutPanel.Controls.Add(optionCLabel, 0, 1);
        optionsLayoutPanel.Controls.Add(optionDLabel, 1, 1);
        optionsLayoutPanel.Dock = DockStyle.Fill;
        optionsLayoutPanel.Name = "optionsLayoutPanel";
        optionsLayoutPanel.RowCount = 2;
        optionsLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        optionsLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
        optionALabel.AutoEllipsis = false;
        optionALabel.Dock = DockStyle.Fill;
        optionALabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        optionALabel.Margin = new Padding(6);
        optionALabel.Name = "optionALabel";
        optionALabel.Padding = new Padding(10);
        optionALabel.Text = "A. —";
        optionALabel.TextAlign = ContentAlignment.MiddleLeft;
        optionBLabel.AutoEllipsis = false;
        optionBLabel.Dock = DockStyle.Fill;
        optionBLabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        optionBLabel.Margin = new Padding(6);
        optionBLabel.Name = "optionBLabel";
        optionBLabel.Padding = new Padding(10);
        optionBLabel.Text = "B. —";
        optionBLabel.TextAlign = ContentAlignment.MiddleLeft;
        optionCLabel.AutoEllipsis = false;
        optionCLabel.Dock = DockStyle.Fill;
        optionCLabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        optionCLabel.Margin = new Padding(6);
        optionCLabel.Name = "optionCLabel";
        optionCLabel.Padding = new Padding(10);
        optionCLabel.Text = "C. —";
        optionCLabel.TextAlign = ContentAlignment.MiddleLeft;
        optionDLabel.AutoEllipsis = false;
        optionDLabel.Dock = DockStyle.Fill;
        optionDLabel.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold);
        optionDLabel.Margin = new Padding(6);
        optionDLabel.Name = "optionDLabel";
        optionDLabel.Padding = new Padding(10);
        optionDLabel.Text = "D. —";
        optionDLabel.TextAlign = ContentAlignment.MiddleLeft;
        practiceCompletePanel.BackColor = Color.FromArgb(255, 248, 230);
        practiceCompletePanel.Controls.Add(practiceCompleteLayoutPanel);
        practiceCompletePanel.Dock = DockStyle.Fill;
        practiceCompletePanel.Name = "practiceCompletePanel";
        practiceCompletePanel.Visible = false;
        practiceCompleteLayoutPanel.ColumnCount = 3;
        practiceCompleteLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        practiceCompleteLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        practiceCompleteLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.33333F));
        practiceCompleteLayoutPanel.Controls.Add(practiceCompleteTitleLabel, 0, 0);
        practiceCompleteLayoutPanel.SetColumnSpan(practiceCompleteTitleLabel, 3);
        practiceCompleteLayoutPanel.Controls.Add(practiceCompleteHintLabel, 0, 1);
        practiceCompleteLayoutPanel.SetColumnSpan(practiceCompleteHintLabel, 3);
        practiceCompleteLayoutPanel.Controls.Add(practiceParticipantCaptionLabel, 0, 2);
        practiceCompleteLayoutPanel.Controls.Add(practiceAnsweredCaptionLabel, 1, 2);
        practiceCompleteLayoutPanel.Controls.Add(practiceNotAnsweredCaptionLabel, 2, 2);
        practiceCompleteLayoutPanel.Controls.Add(practiceParticipantValueLabel, 0, 3);
        practiceCompleteLayoutPanel.Controls.Add(practiceAnsweredValueLabel, 1, 3);
        practiceCompleteLayoutPanel.Controls.Add(practiceNotAnsweredValueLabel, 2, 3);
        practiceCompleteLayoutPanel.Dock = DockStyle.Fill;
        practiceCompleteLayoutPanel.Name = "practiceCompleteLayoutPanel";
        practiceCompleteLayoutPanel.Padding = new Padding(30);
        practiceCompleteLayoutPanel.RowCount = 4;
        practiceCompleteLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 35F));
        practiceCompleteLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        practiceCompleteLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 15F));
        practiceCompleteLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 30F));
        practiceCompleteTitleLabel.Dock = DockStyle.Fill;
        practiceCompleteTitleLabel.Font = new Font("Microsoft JhengHei UI", 24F, FontStyle.Bold);
        practiceCompleteTitleLabel.Name = "practiceCompleteTitleLabel";
        practiceCompleteTitleLabel.Text = "操作練習完成";
        practiceCompleteTitleLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceCompleteHintLabel.Dock = DockStyle.Fill;
        practiceCompleteHintLabel.Name = "practiceCompleteHintLabel";
        practiceCompleteHintLabel.Text = "確認現場參與狀態後，使用下方主要按鈕開始正式比賽。";
        practiceCompleteHintLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceParticipantCaptionLabel.Dock = DockStyle.Fill;
        practiceParticipantCaptionLabel.Name = "practiceParticipantCaptionLabel";
        practiceParticipantCaptionLabel.Text = "Participants";
        practiceParticipantCaptionLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceAnsweredCaptionLabel.Dock = DockStyle.Fill;
        practiceAnsweredCaptionLabel.Name = "practiceAnsweredCaptionLabel";
        practiceAnsweredCaptionLabel.Text = "Answered Practice";
        practiceAnsweredCaptionLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceNotAnsweredCaptionLabel.Dock = DockStyle.Fill;
        practiceNotAnsweredCaptionLabel.Name = "practiceNotAnsweredCaptionLabel";
        practiceNotAnsweredCaptionLabel.Text = "Not Answered";
        practiceNotAnsweredCaptionLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceParticipantValueLabel.Dock = DockStyle.Fill;
        practiceParticipantValueLabel.Font = new Font("Microsoft JhengHei UI", 22F, FontStyle.Bold);
        practiceParticipantValueLabel.Name = "practiceParticipantValueLabel";
        practiceParticipantValueLabel.Text = "0";
        practiceParticipantValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceAnsweredValueLabel.Dock = DockStyle.Fill;
        practiceAnsweredValueLabel.Font = new Font("Microsoft JhengHei UI", 22F, FontStyle.Bold);
        practiceAnsweredValueLabel.Name = "practiceAnsweredValueLabel";
        practiceAnsweredValueLabel.Text = "0";
        practiceAnsweredValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        practiceNotAnsweredValueLabel.Dock = DockStyle.Fill;
        practiceNotAnsweredValueLabel.Font = new Font("Microsoft JhengHei UI", 22F, FontStyle.Bold);
        practiceNotAnsweredValueLabel.Name = "practiceNotAnsweredValueLabel";
        practiceNotAnsweredValueLabel.Text = "0";
        practiceNotAnsweredValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        resultTabPage.Controls.Add(resultLayoutPanel);
        resultTabPage.Name = "resultTabPage";
        resultTabPage.Text = "結果";
        resultLayoutPanel.ColumnCount = 1;
        resultLayoutPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        resultLayoutPanel.Controls.Add(correctAnswerValueLabel, 0, 0);
        resultLayoutPanel.Controls.Add(resultSummaryValueLabel, 0, 1);
        resultLayoutPanel.Controls.Add(explanationTextBox, 0, 2);
        resultLayoutPanel.Controls.Add(distributionGrid, 0, 3);
        resultLayoutPanel.Dock = DockStyle.Fill;
        resultLayoutPanel.Name = "resultLayoutPanel";
        resultLayoutPanel.Padding = new Padding(12);
        resultLayoutPanel.RowCount = 4;
        resultLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        resultLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
        resultLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
        resultLayoutPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        correctAnswerValueLabel.Dock = DockStyle.Fill;
        correctAnswerValueLabel.Font = new Font("Microsoft JhengHei UI", 18F, FontStyle.Bold);
        correctAnswerValueLabel.ForeColor = Color.DarkGreen;
        correctAnswerValueLabel.Name = "correctAnswerValueLabel";
        correctAnswerValueLabel.Text = "等待公布";
        correctAnswerValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        resultSummaryValueLabel.Dock = DockStyle.Fill;
        resultSummaryValueLabel.Name = "resultSummaryValueLabel";
        resultSummaryValueLabel.Text = "尚無結果";
        resultSummaryValueLabel.TextAlign = ContentAlignment.MiddleCenter;
        explanationTextBox.Dock = DockStyle.Fill;
        explanationTextBox.Multiline = true;
        explanationTextBox.Name = "explanationTextBox";
        explanationTextBox.ReadOnly = true;
        distributionGrid.AllowUserToAddRows = false;
        distributionGrid.AllowUserToDeleteRows = false;
        distributionGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        distributionGrid.Columns.AddRange(
            new DataGridViewTextBoxColumn { HeaderText = "選項", FillWeight = 80 },
            new DataGridViewTextBoxColumn { HeaderText = "人數", FillWeight = 20 });
        distributionGrid.Dock = DockStyle.Fill;
        distributionGrid.Name = "distributionGrid";
        distributionGrid.ReadOnly = true;
        distributionGrid.RowHeadersVisible = false;
        leaderboardTabPage.Controls.Add(leaderboardGrid);
        leaderboardTabPage.Name = "leaderboardTabPage";
        leaderboardTabPage.Text = "排行榜";
        leaderboardGrid.AllowUserToAddRows = false;
        leaderboardGrid.AllowUserToDeleteRows = false;
        leaderboardGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        leaderboardGrid.Columns.AddRange(
            new DataGridViewTextBoxColumn { HeaderText = "名次" },
            new DataGridViewTextBoxColumn { HeaderText = "顯示名稱", FillWeight = 180 },
            new DataGridViewTextBoxColumn { HeaderText = "總分" },
            new DataGridViewTextBoxColumn { HeaderText = "答對" },
            new DataGridViewTextBoxColumn { HeaderText = "作答" });
        leaderboardGrid.Dock = DockStyle.Fill;
        leaderboardGrid.Name = "leaderboardGrid";
        leaderboardGrid.ReadOnly = true;
        leaderboardGrid.RowHeadersVisible = false;
        countdownTimer.Interval = 250;
        countdownTimer.Tick += countdownTimer_Tick;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.White;
        Controls.Add(rootLayoutPanel);
        Name = "QuizActivityView";
        Padding = new Padding(18);
        Size = new Size(850, 680);
        rootLayoutPanel.ResumeLayout(false);
        contextLayoutPanel.ResumeLayout(false);
        bodyLayoutPanel.ResumeLayout(false);
        questionListGroupBox.ResumeLayout(false);
        questionListLayoutPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)questionListGrid).EndInit();
        activityTabControl.ResumeLayout(false);
        questionTabPage.ResumeLayout(false);
        questionContentLayoutPanel.ResumeLayout(false);
        optionsLayoutPanel.ResumeLayout(false);
        practiceCompletePanel.ResumeLayout(false);
        practiceCompleteLayoutPanel.ResumeLayout(false);
        resultTabPage.ResumeLayout(false);
        resultLayoutPanel.ResumeLayout(false);
        resultLayoutPanel.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)distributionGrid).EndInit();
        leaderboardTabPage.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)leaderboardGrid).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel rootLayoutPanel;
    private Label titleLabel;
    private TableLayoutPanel contextLayoutPanel;
    private Label quizTitleCaptionLabel;
    private Label quizTitleValueLabel;
    private Label modeCaptionLabel;
    private Label modeValueLabel;
    private Label questionNumberCaptionLabel;
    private Label questionNumberValueLabel;
    private Label stateCaptionLabel;
    private Label stateValueLabel;
    private Label progressValueLabel;
    private Label countdownValueLabel;
    private TableLayoutPanel bodyLayoutPanel;
    private GroupBox questionListGroupBox;
    private TableLayoutPanel questionListLayoutPanel;
    private Button defaultPracticeButton;
    private DataGridView questionListGrid;
    private TabControl activityTabControl;
    private TabPage questionTabPage;
    private TableLayoutPanel questionContentLayoutPanel;
    private Label questionTextLabel;
    private TableLayoutPanel optionsLayoutPanel;
    private Label optionALabel;
    private Label optionBLabel;
    private Label optionCLabel;
    private Label optionDLabel;
    private Panel practiceCompletePanel;
    private TableLayoutPanel practiceCompleteLayoutPanel;
    private Label practiceCompleteTitleLabel;
    private Label practiceCompleteHintLabel;
    private Label practiceParticipantCaptionLabel;
    private Label practiceParticipantValueLabel;
    private Label practiceAnsweredCaptionLabel;
    private Label practiceAnsweredValueLabel;
    private Label practiceNotAnsweredCaptionLabel;
    private Label practiceNotAnsweredValueLabel;
    private TabPage resultTabPage;
    private TableLayoutPanel resultLayoutPanel;
    private Label correctAnswerValueLabel;
    private Label resultSummaryValueLabel;
    private TextBox explanationTextBox;
    private DataGridView distributionGrid;
    private TabPage leaderboardTabPage;
    private DataGridView leaderboardGrid;
    private System.Windows.Forms.Timer countdownTimer;
}
